"""``bty-lab init`` -- emit a ready-to-run podman/docker compose
deployment of bty-web + withcache (with an optional Quadlet variant for
systemd auto-start).

The intent is to turn the first-boot ergonomics of a bty + withcache
host from "clone the repo, find the right files" into:

    uvx bty-lab init ./bty-host
    cd bty-host
    cp envvars.example envvars && "${EDITOR:-vi}" envvars
    podman compose up -d

The emitted ``compose.yml`` pins ``bty-web`` and ``bty-tftp`` to the
*exact* version of the CLI that produced it -- re-running the command
later regenerates the file against a newer release. ``withcache`` is an
external project and stays at ``:latest`` (it does not share bty's
release cadence).

``bty-lab`` is a separate console script from ``bty`` on purpose: the
flash wizard wants to stay single-purpose, and matching the script name
to the PyPI distribution lets ``uvx bty-lab ...`` and
``pipx run bty-lab ...`` work without ``--from``.

This module imports nothing from the ``[web]`` / ``[tui]`` extras so a
bare ``uvx bty-lab`` suffices to run it.
"""

from __future__ import annotations

import argparse
import os
import secrets
import shutil
import socket
import subprocess
import sys
from pathlib import Path

import bty

# Where Quadlet units land on a system-wide podman install. Files dropped
# here are picked up by the podman-system-generator on `systemctl
# daemon-reload`.
QUADLET_SYSTEM_DIR = Path("/etc/containers/systemd")

# Service names the Quadlet units in this module generate. Used by
# `deploy` (as root: start them) and `upgrade` (detect Quadlet-managed
# stack + restart).
_SYSTEMD_SERVICES = ("withcache.service", "bty-web.service", "bty-tftp.service")

DEFAULT_DEST = Path("./bty-host")


def _compose_yaml(version: str) -> str:
    """Render the compose.yml body for ``version``."""
    return f"""\
# Generated by `bty-lab init` (bty {version}).
# Re-run that command later (with --force) to refresh against a newer
# bty release; the bty-web / bty-tftp image tags below match the CLI
# version that emitted this file.
#
# Quickstart:
#   cp envvars.example envvars
#   "${{EDITOR:-vi}}" envvars                                  # set HOST_ADDR + passwords
#   export COMPOSE_ENV_FILES=envvars                           # once per shell, then:
#   podman compose up -d                                       # bty:       http://<host>:8080/ui
#                                                              # withcache: http://<host>:3000/
#
# (Without the export, pass --env-file envvars on every compose call.)
#
# BIOS PXE clients also need TFTP (UEFI HTTP-Boot does not):
#   podman compose --profile tftp up -d
#
# Upgrade:
#   uvx bty-lab init --force .                                 # regenerate against newer bty
#   podman compose pull && podman compose up -d
#
# Host state lives under ${{BTY_HOST_DATA_DIR:-./data}} -- bty under
# bty/, withcache under withcache/. Move/back-up those dirs to migrate
# to another host.

services:
  withcache:
    image: ghcr.io/safl/withcache:latest
    restart: unless-stopped
    # Hard-set the resolver so this works on stock Ubuntu hosts where
    # systemd-resolved owns /etc/resolv.conf and aardvark-dns isn't
    # installed. Override BTY_DNS in envvars to point at an internal
    # resolver if the host is on a corporate LAN.
    dns:
      - ${{BTY_DNS:-1.1.1.1}}
    ports:
      - "3000:3000"
    environment:
      WITHCACHE_ADMIN_PASSWORD: ${{WITHCACHE_ADMIN_PASSWORD:?set in envvars}}
    volumes:
      - ${{BTY_HOST_DATA_DIR:-./data}}/withcache:/data

  bty-web:
    image: ghcr.io/safl/bty-web:{version}
    restart: unless-stopped
    # See note on withcache.dns -- same reason.
    dns:
      - ${{BTY_DNS:-1.1.1.1}}
    ports:
      - "8080:8080"
    environment:
      # v0.42+: bty-web reads operator config from this TOML file.
      # The bind-mount below makes it visible to the container; the
      # operator edits ./bty.toml directly (or via the Settings page).
      # Per-key env overrides (BTY_<SECTION>_<KEY>) still work for
      # one-shot dev runs / k8s Secrets, but the canonical authoring
      # path is the file.
      BTY_CONFIG_FILE: /etc/bty/bty.toml
    volumes:
      - ${{BTY_HOST_DATA_DIR:-./data}}/bty:/var/lib/bty
      # RW (no :ro) so Settings-page edits land back on the host file,
      # matching the Quadlet unit's mount.
      - ./bty.toml:/etc/bty/bty.toml
    depends_on:
      - withcache

  tftp:
    image: ghcr.io/safl/bty-tftp:{version}
    profiles: ["tftp"]
    restart: unless-stopped
    # TFTP's data transfer hops to an ephemeral UDP port, so the sidecar
    # uses host networking. The NBPs (incl. bty's embedded-chain
    # ipxe.efi) are baked into the image -- no volume, no shared data.
    network_mode: host
"""


def _env_example(default_data_dir: str) -> str:
    """Render the envvars.example body."""
    return f"""\
# Copy to envvars and edit. The compose file refuses to start unless
# HOST_ADDR and WITHCACHE_ADMIN_PASSWORD are set; everything below
# the REQUIRED block has a sane default and stays empty/unset unless
# you uncomment.

# ==== REQUIRED ====

# This host's LAN address. Booting clients fetch images + boot scripts
# from here, so it MUST be reachable from those machines -- NOT
# 127.0.0.1, NOT a container name.
HOST_ADDR=10.0.0.5

# Operator login for the withcache UI at http://<host>:3000/.
WITHCACHE_ADMIN_PASSWORD=change-me

# ==== STRONGLY RECOMMENDED ====

# Gates the bty-web operator UI at http://<host>:8080/ui (constant-
# time password compare). UNSET = UI open (bty-web logs a startup
# warning on first boot). Set this before exposing past a trusted
# LAN.
# BTY_ADMIN_PASSWORD=change-me

# ==== COMMON CUSTOMISATIONS ====

# Where state lives on the host. Default: ./data (relative to this
# directory). Point at a bigger disk for larger fleets:
# BTY_HOST_DATA_DIR={default_data_dir}

# Resolver bty-web + withcache use for outbound DNS (GitHub release
# artifacts, GHCR blob pulls). Default: 1.1.1.1, which sidesteps
# stock-Ubuntu hosts where /etc/resolv.conf points at the
# systemd-resolved stub (127.0.0.53) that containers can't reach.
# Set to an internal resolver if the host is on a corporate LAN.
# BTY_DNS=192.168.1.1

# ==== ADVANCED ====

# Override which GitHub repo bty fetches netboot artifacts (live env
# kernel/initrd/squashfs) from. Default: safl/bty. Useful when running
# off a fork or a private mirror.
# BTY_BOOT_RELEASE_REPO=your-fork/bty

# Trust the X-Forwarded-* headers from this CIDR or single address
# (set when bty-web sits behind nginx / traefik / Caddy so it can
# recover the original client's address + scheme for audit logs and
# absolute-URL generation). Default: unset (no header trust).
# BTY_TRUSTED_PROXY=10.0.0.0/8

# Pin a stable bty-web session-cookie secret. Default: a fresh random
# secret generated and persisted in state.db on first start (re-used
# across container restarts). Override only if you need the secret to
# be reproducible (multi-instance, blue/green) or rotated on a
# schedule.
# BTY_SESSION_SECRET=<32-byte hex>

# Per-request upload cap for the operator UI's image-upload form.
# Default: 200 GiB. Bump for very large images, drop for small
# fleets or untrusted networks.
# BTY_MAX_UPLOAD_BYTES=214748364800

# Concurrent-worker caps. Defaults are sane for most fleets; raise
# carefully if the host has the CPU + disk bandwidth, drop on small
# boxes (Raspberry Pi, low-spec mini-PCs).
# BTY_CATALOG_MAX_PARALLEL=2
# BTY_HASH_MAX_PARALLEL=1
# BTY_BACKUP_MAX_PARALLEL=1
"""


def _readme(version: str, *, with_systemd: bool) -> str:
    """Render the in-tree README the deploy dir ships with."""
    systemd_section = ""
    if with_systemd:
        systemd_section = """\

## Auto-start on boot (systemd via Quadlet)

The `quadlet/` directory holds Podman Quadlet units that systemd
generates services from. Install:

```sh
sudo cp quadlet/*.container /etc/containers/systemd/
sudo systemctl daemon-reload
sudo systemctl start withcache.service bty-web.service
# Optional, for BIOS PXE clients:
sudo systemctl start bty-tftp.service
```

`AutoUpdate=registry` lets `podman auto-update` (enable the
`podman-auto-update.timer`) pull new images and restart the services.
The units reference absolute paths under the `data/` directory next to
this README -- the path was baked in at `bty-lab` time. Move the
directory only by regenerating with `--data-dir <new-path>`.
"""

    return f"""\
# bty deploy

Generated by `bty-lab init` (bty {version}).

## Prerequisites

- `podman` (or `docker`).
- A compose backend. `podman compose` is a thin wrapper that
  auto-discovers one of `docker-compose`, `podman-compose`, or the
  docker compose plugin from PATH. If none is installed,
  `podman compose up -d` errors with "looking up compose provider
  failed". Fix: `pipx install podman-compose` (the lightest option).

## Quickstart

```sh
cp envvars.example envvars
"${{EDITOR:-vi}}" envvars                       # set HOST_ADDR + passwords

# Tell compose which env-file to load (once per shell):
export COMPOSE_ENV_FILES=envvars

podman compose up -d                            # bty:       http://<host>:8080/ui
                                                # withcache: http://<host>:3000/
```

If you'd rather not set the env var, pass ``--env-file envvars`` on
every compose call: ``podman compose --env-file envvars up -d``.

For BIOS PXE clients that bootstrap over TFTP (UEFI HTTP-Boot does
not):

```sh
podman compose up -d --profile tftp
```

bty-web auto-discovers withcache from the `BTY_WITHCACHE_URL` env var
that the compose file sets, so first-boot needs no UI configuration --
just `HOST_ADDR` + a password in `envvars`.

## Where the state lives

- `data/bty/`       -- bty-web's `/var/lib/bty` (state.db, catalogs,
  netboot artifacts, backups). Bind-mounted into the container.
- `data/withcache/` -- withcache's `/data` (cached image blobs).

Override the parent path with `BTY_HOST_DATA_DIR=<absolute-path>` in
`envvars` to put state on a different disk.

## Upgrade

```sh
uvx bty-lab init --force .           # regenerate compose for newer bty
podman compose pull && podman compose up -d
```

The compose file pins bty-web / bty-tftp to the bty version that
generated this directory; re-running `bty-lab` with a newer bty CLI
bumps those pins. State in `data/` survives the restart.
{systemd_section}"""


def _quadlet_bty_web(
    version: str,
    data_dir_abs: Path,
    host_addr: str | None = None,
    dest_abs: Path | None = None,
) -> str:
    """Render the bty-web Quadlet unit.

    ``host_addr`` baked in when known (deploy_main path): the unit lands
    with the real LAN IP in BTY_WITHCACHE_URL + BTY_TFTP_PROBE_HOST, so
    no hand-edit is required. ``None`` (the stand-alone ``bty-lab init
    --systemd`` path -- operator inspects + edits before installing)
    emits ``HOST_ADDR_HERE`` placeholders and a hand-edit note in the
    header. Quadlets DON'T expand env-file references the way Compose
    does, so a literal placeholder would leave bty-web with broken DNS
    + a failing TFTP probe; substituting at emit time is the only place
    in the pipeline that has the value.
    """
    edit_note = (
        ""
        if dest_abs is not None
        else (
            "# Edit ``Volume=`` below: replace BTY_TOML_HOST_PATH_HERE with the\n"
            "# absolute path to ``bty.toml`` on this host before installing.\n#\n"
        )
    )
    # ``host_addr`` is no longer baked into Environment= lines --
    # v0.42 moved every operator knob into bty.toml. Kept as a
    # signature arg for one release in case a downstream still calls
    # with it positionally; we explicitly ignore it.
    _ = host_addr
    toml_host_path = (
        str(dest_abs / "bty.toml") if dest_abs is not None else "BTY_TOML_HOST_PATH_HERE"
    )
    return f"""\
# Generated by `bty-lab init --systemd` (bty {version}).
# Install: sudo cp this file into /etc/containers/systemd/ then run
#   sudo systemctl daemon-reload && sudo systemctl start bty-web.service
#
{edit_note}[Unit]
Description=bty-web
After=network-online.target withcache.service
Wants=network-online.target

[Container]
Image=ghcr.io/safl/bty-web:{version}
AutoUpdate=registry
PublishPort=8080:8080
Volume={data_dir_abs}/bty:/var/lib/bty:Z
# v0.42+: operator config is a TOML file at ``<dest>/bty.toml``,
# bind-mounted at ``/etc/bty/bty.toml``. Edit that file directly
# or via the Settings page (the UI round-trips edits through
# tomlkit). bty-web re-reads on each restart. The mount is RW
# (no ``:ro``) so Settings writes land back on the host file.
Volume={toml_host_path}:/etc/bty/bty.toml:Z
Environment=BTY_CONFIG_FILE=/etc/bty/bty.toml
# Hard-set DNS so external lookups work on stock Ubuntu hosts where
# systemd-resolved owns /etc/resolv.conf and aardvark-dns isn't
# installed. Edit if the host needs an internal resolver.
DNS=1.1.1.1

[Service]
Restart=always

[Install]
WantedBy=multi-user.target default.target
"""


def _quadlet_withcache(version: str, data_dir_abs: Path) -> str:
    return f"""\
# Generated by `bty-lab init --systemd` (bty {version}).
# Install: sudo cp this file into /etc/containers/systemd/ then run
#   sudo systemctl daemon-reload && sudo systemctl start withcache.service
#
# Edit Environment=WITHCACHE_ADMIN_PASSWORD before installing.

[Unit]
Description=withcache cache-host
After=network-online.target
Wants=network-online.target

[Container]
Image=ghcr.io/safl/withcache:latest
AutoUpdate=registry
PublishPort=3000:3000
Volume={data_dir_abs}/withcache:/data:Z
# See note on bty-web's DNS= -- same reason.
DNS=1.1.1.1
Environment=WITHCACHE_ADMIN_PASSWORD=change-me

[Service]
Restart=always

[Install]
WantedBy=multi-user.target default.target
"""


def _quadlet_bty_tftp(version: str) -> str:
    return f"""\
# Generated by `bty-lab init --systemd` (bty {version}).
# Optional: install only if BIOS clients PXE-boot via TFTP. UEFI
# HTTP-Boot does not need this sidecar.

[Unit]
Description=bty TFTP sidecar (BIOS PXE bootstrap)
After=network-online.target
Wants=network-online.target

[Container]
Image=ghcr.io/safl/bty-tftp:{version}
AutoUpdate=registry
# TFTP data transfer uses an ephemeral UDP port; host networking is the
# simplest way to make that work. The NBPs are baked into the image.
Network=host

[Service]
Restart=always

[Install]
WantedBy=multi-user.target default.target
"""


def _write(path: Path, body: str, *, force: bool) -> None:
    """Write ``body`` to ``path``, creating parents. Refuse to overwrite
    unless ``force`` is True."""
    if path.exists() and not force:
        raise FileExistsError(
            f"{path} already exists; pass --force to overwrite "
            f"(re-runs of bty-lab re-render every file)."
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


# ---- Shared deploy-file emission --------------------------------------------


def _emit_deploy_files(
    dest: Path,
    *,
    data_dir_abs: Path,
    version: str,
    with_systemd: bool,
    force: bool,
    host_addr: str | None = None,
) -> list[Path]:
    """Emit compose.yml + envvars.example + README + (optional) Quadlet
    units into ``dest``. Returns the list of paths written.

    Raises ``FileExistsError`` if a file exists and ``force`` is False,
    or ``PermissionError`` if the operator can't write ``dest``. Callers
    surface those with their own messaging."""
    written: list[Path] = []

    compose_path = dest / "compose.yml"
    _write(compose_path, _compose_yaml(version), force=force)
    written.append(compose_path)

    env_path = dest / "envvars.example"
    _write(env_path, _env_example(str(data_dir_abs)), force=force)
    written.append(env_path)

    readme_path = dest / "README.md"
    _write(readme_path, _readme(version, with_systemd=with_systemd), force=force)
    written.append(readme_path)

    if with_systemd:
        quadlet_dir = dest / "quadlet"
        dest_abs = dest.resolve()
        for fname, body in (
            (
                "bty-web.container",
                _quadlet_bty_web(version, data_dir_abs, host_addr, dest_abs=dest_abs),
            ),
            ("withcache.container", _quadlet_withcache(version, data_dir_abs)),
            ("bty-tftp.container", _quadlet_bty_tftp(version)),
        ):
            p = quadlet_dir / fname
            _write(p, body, force=force)
            written.append(p)

    # Pre-create the bind-mount roots so podman doesn't create them as
    # root-owned and so the operator can see where state will land
    # without starting the stack first.
    data_dir = data_dir_abs if data_dir_abs.is_absolute() else dest / "data"
    (data_dir / "bty").mkdir(parents=True, exist_ok=True)
    (data_dir / "withcache").mkdir(parents=True, exist_ok=True)

    return written


# ---- Auto-fill envvars + host probe -----------------------------------------


def _parse_envvars(envvars_path: Path) -> dict[str, str]:
    """Read a v0.41-style envvars file into a plain ``key=value``
    dict. Comments (``#``) + blank lines skipped; quoted values are
    unwrapped of one outer layer of quotes. Returns ``{}`` if the
    file is unreadable so callers can treat that as "no overrides
    to carry across"."""
    out: dict[str, str] = {}
    try:
        text = envvars_path.read_text(encoding="utf-8")
    except OSError:
        return out
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        v = value.strip().strip('"').strip("'")
        out[key.strip()] = v
    return out


def _envvars_to_bty_toml(envvars_path: Path, host_addr: str) -> str:
    """Translate a v0.41 ``envvars`` file into the v0.42 ``bty.toml``
    shape an in-place upgrade should land.

    Reads the envvars file, picks every BTY_* key the upgrade should
    carry across (per :data:`_ENVVARS_TO_TOML`), and emits a bty.toml
    matching :func:`_render_bty_toml`'s shape -- with the operator's
    actual values where set, schema defaults otherwise. ``host_addr``
    seeds the [withcache] url + [netboot] tftp_probe_host (those were
    derived from HOST_ADDR via compose substitution in v0.41; the
    bty.toml shape stores them as concrete strings).
    """
    env = _parse_envvars(envvars_path)
    admin_pw = env.get("BTY_ADMIN_PASSWORD") or "bty"
    session_secret = env.get("BTY_SESSION_SECRET") or _gen_secret(32)
    server_host = env.get("BTY_WEB_HOST") or "0.0.0.0"
    server_port = env.get("BTY_WEB_PORT") or "8080"
    trusted_proxy = env.get("BTY_TRUSTED_PROXY") or ""
    state_dir = env.get("BTY_STATE_DIR") or "/var/lib/bty"
    boot_dir = env.get("BTY_BOOT_DIR") or ""
    backup_dir = env.get("BTY_BACKUP_DIR") or ""
    catalog_file = env.get("BTY_CATALOG_FILE") or ""
    withcache_url = env.get("BTY_WITHCACHE_URL") or f"http://{host_addr}:3000"
    tftp_probe = env.get("BTY_TFTP_PROBE_HOST") or host_addr

    def _opt(key: str, value: str) -> str:
        """Render an optional string field: comment-out when blank
        (so the schema default takes over) else set to the value."""
        return f'{key} = "{value}"' if value else f'# {key} = ""'

    return f"""\
# bty.toml migrated from envvars by ``bty-lab upgrade``.
# Edit freely; bty-web re-reads on each restart. The Settings page
# also round-trips edits through tomlkit so your comments survive.

[admin]
password = "{admin_pw}"

[server]
host = "{server_host}"
port = {server_port}
{_opt("trusted_proxy", trusted_proxy)}
session_secret = "{session_secret}"

[paths]
state_dir = "{state_dir}"
{_opt("boot_dir", boot_dir)}
{_opt("backup_dir", backup_dir)}
{_opt("catalog_file", catalog_file)}

[withcache]
url = "{withcache_url}"

[netboot]
tftp_probe_host = "{tftp_probe}"

[release]
# Pinned in state.db (Settings -> Upstream sources); these defaults
# seed a fresh install.

[tuning]
# backup_max_parallel = 1
# max_upload_bytes = 214748364800
"""


def _read_envvars_host_addr(envvars_path: Path) -> str:
    """Read ``HOST_ADDR=...`` back out of the preserved envvars file.

    Used by ``upgrade_main`` so a regenerated Quadlet picks up the same
    LAN IP the operator committed to at deploy time. Falls back to
    :func:`_detect_host_addr` when the file is unreadable / malformed /
    missing the key -- mirrors deploy-time behaviour rather than
    crashing the upgrade.
    """
    try:
        for raw in envvars_path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            if key.strip() == "HOST_ADDR":
                v = value.strip().strip('"').strip("'")
                if v:
                    return v
    except OSError:
        pass
    return _detect_host_addr()


def _detect_host_addr() -> str:
    """Best-effort LAN IP detection.

    UDP-connects to a TEST-NET-2 address (no packet sent on UDP-connect;
    the kernel just chooses an outbound interface) and reads the local
    socket address. Returns whichever IP the host would actually use for
    outbound traffic -- almost always the LAN address bty-web should
    advertise. Falls back to ``127.0.0.1`` when no route is available;
    the deploy hint surfaces this so the operator can override."""
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        s.connect(("198.51.100.1", 80))
        # getsockname() returns Any per typeshed (the tuple shape
        # depends on the address family); coerce to str for the
        # IPv4 case we constructed the socket for.
        addr: str = s.getsockname()[0]
        return addr
    except OSError:
        return "127.0.0.1"
    finally:
        s.close()


def _gen_secret(nbytes: int = 24) -> str:
    """URL-safe random token. ``nbytes`` of entropy."""
    return secrets.token_urlsafe(nbytes)


def _render_bty_toml(
    *,
    host_addr: str,
    admin_pw: str,
    session_secret: str,
) -> str:
    """Render the operator-facing ``bty.toml`` (v0.42+ canonical
    config). The compose / Quadlet only carry ``BTY_CONFIG_FILE``
    + a bind-mount of this file; everything else is here.

    Every key has a sane default in the loader's schema, so leaving
    a section blank is fine. The values we DO fill in are the ones
    a fresh deploy can't auto-derive sensibly: ``host_addr`` (LAN IP
    bty-web advertises to PXE clients), the admin password +
    session secret. Sections without operator-required content
    stay as commented headers so the operator sees the shape of
    what's available.

    Operator edits the file directly (or via the Settings page
    write-back); restart bty-web to pick up changes.
    """
    return f"""\
# bty-web operator config (TOML). Edit freely; bty-web re-reads
# on each restart. The Settings page also round-trips edits
# through tomlkit so your comments + ordering survive.
#
# Layered config: built-in defaults < this file < env vars
# (BTY_<SECTION>_<KEY>; e.g. BTY_ADMIN_PASSWORD overrides
# [admin] password). Useful for k8s Secrets or one-shot dev runs
# where you don't want secrets sitting in TOML on disk.
#
# Drop-ins: anything under ./conf.d/*.toml overrides this file
# (lexicographic order). Conventional split: bty.toml in git,
# conf.d/99-secrets.toml mode 0600 outside it.

[admin]
# Gates the operator UI at http://<host>:8080/ui.
password = "{admin_pw}"

[server]
host = "0.0.0.0"
port = 8080
# trusted_proxy = "10.0.0.0/8"    # when behind a reverse proxy
# Pinned session secret so cookies survive container restarts;
# leave blank to auto-generate + persist to <state_dir>/session-secret.
session_secret = "{session_secret}"

[paths]
state_dir = "/var/lib/bty"
# boot_dir / backup_dir / catalog_file default to <state_dir>/...;
# override only when state should live on a bigger disk than the
# OS root.

[withcache]
# bty-web routes catalog reads through withcache when this is set.
# Blank => bty-web streams from origin URLs directly.
url = "http://{host_addr}:3000"

[netboot]
# Where the /ui/netboot diagnostic probes TFTP. The bty-tftp
# sidecar binds host networking, so this is the host's LAN IP
# (NOT bty-web's own loopback).
tftp_probe_host = "{host_addr}"

[release]
# v0.41-style release-pin lives in state.db (Settings -> Upstream
# sources); these defaults seed a fresh install. Operator changes
# in the UI persist to the DB, not back here.

[tuning]
# Concurrency + size limits. Defaults usually fine.
# backup_max_parallel = 1
# max_upload_bytes = 214748364800   # 200 GiB
"""


def _render_envvars_filled(
    *,
    host_addr: str,
    withcache_pw: str,
    admin_pw: str,
    session_secret: str,
    data_dir_abs: str,
) -> str:
    """Render an envvars file with the required + recommended fields
    filled in. Operator-tweakable optional knobs stay commented out --
    same shape as :func:`_env_example` so the two files stay
    diff-friendly."""
    return f"""\
# Generated by `bty-lab deploy`. Overwrites with `--force`.
# HOST_ADDR + WITHCACHE_ADMIN_PASSWORD are required. The rest below
# the REQUIRED block has sane defaults and stays commented unless you
# need to override.

# ==== REQUIRED ====

HOST_ADDR={host_addr}
WITHCACHE_ADMIN_PASSWORD={withcache_pw}

# ==== STRONGLY RECOMMENDED ====

# Gates the bty-web operator UI at http://<host>:8080/ui.
BTY_ADMIN_PASSWORD={admin_pw}

# Pinned session secret so cookies survive container restarts.
BTY_SESSION_SECRET={session_secret}

# ==== COMMON CUSTOMISATIONS ====

# Where state lives on the host. Default: ./data (relative to this
# directory). Point at a bigger disk for larger fleets:
# BTY_HOST_DATA_DIR={data_dir_abs}

# Resolver bty-web + withcache use for outbound DNS. Default: 1.1.1.1,
# which sidesteps stock-Ubuntu hosts where /etc/resolv.conf points at
# 127.0.0.53. Set to an internal resolver if needed.
# BTY_DNS=192.168.1.1

# ==== ADVANCED ====

# Where bty-web finds withcache. Default: http://<HOST_ADDR>:3000
# (the host's LAN address + the published withcache port). Override
# only if withcache lives on a different host than bty-web.
# BTY_WITHCACHE_URL=http://withcache.lan:3000

# Where bty-web's Netboot-page diagnostic probes for TFTP. Default:
# HOST_ADDR (the bty-tftp sidecar binds host networking, so udp/69
# sits on the host's LAN address). Override if TFTP runs elsewhere,
# e.g. on the LAN router or a dedicated PXE host.
# BTY_TFTP_PROBE_HOST=192.168.1.1

# Override which GitHub repo bty fetches netboot artifacts from.
# BTY_BOOT_RELEASE_REPO=your-fork/bty

# Trust X-Forwarded-* from this CIDR (set when behind a reverse proxy).
# BTY_TRUSTED_PROXY=10.0.0.0/8

# Per-request upload cap for the operator UI's image-upload form.
# BTY_MAX_UPLOAD_BYTES=214748364800

# Concurrent-worker caps.
# BTY_CATALOG_MAX_PARALLEL=2
# BTY_HASH_MAX_PARALLEL=1
# BTY_BACKUP_MAX_PARALLEL=1
"""


# ---- Visual step printer + subprocess wrappers ------------------------------


# Module-level step counter, set up by :func:`_steps_begin` and bumped
# by every :func:`_step` call. Lives in module state (rather than being
# threaded through every helper) so the existing ``_step(...)`` call
# sites stay one-liners. Deploy / upgrade are not re-entrant, so the
# global is safe in practice.
_STEP_CURRENT = 0
_STEP_TOTAL = 0


def _steps_begin(total: int) -> None:
    """Reset the step counter and set the total for ``[N/M]`` headers.

    Call once at the top of :func:`deploy_main` / :func:`upgrade_main`
    after the mode-detection logic has decided how many steps the run
    will fire (root/non-root + sudo-chown + Quadlet-managed all swing
    the total)."""
    global _STEP_CURRENT, _STEP_TOTAL
    _STEP_CURRENT = 0
    _STEP_TOTAL = total


def _step(label: str, *, detail: str | None = None) -> None:
    """Print a visible phase boundary, prefixed with ``[N/M]`` when
    :func:`_steps_begin` has been called, or ``==>`` otherwise.
    Subprocess output that follows streams through to stderr so the
    operator sees what's happening between boundaries."""
    global _STEP_CURRENT
    _STEP_CURRENT += 1
    prefix = f"[{_STEP_CURRENT}/{_STEP_TOTAL}]" if _STEP_TOTAL > 0 else "==>"
    if detail is not None:
        print(f"{prefix} {label}: {detail}", file=sys.stderr)
    else:
        print(f"{prefix} {label}", file=sys.stderr)


def _require_prereqs(*, with_systemd: bool, prog: str) -> str:
    """Verify podman + a compose backend are on PATH, and (with
    ``with_systemd``) that systemctl is too AND the operator is root.
    Returns the compose backend's display name for the step output.

    Refuses with sys.exit on any missing piece. ``-f`` does NOT bypass
    this -- the deploy genuinely can't proceed without these."""
    if shutil.which("podman") is None:
        print(
            f"{prog}: podman is not on PATH. Install it first:\n"
            "  # Debian / Ubuntu:  sudo apt install podman\n"
            "  # Fedora / RHEL:    sudo dnf install podman",
            file=sys.stderr,
        )
        sys.exit(1)

    backend = None
    if shutil.which("podman-compose") is not None:
        backend = "podman-compose"
    elif shutil.which("docker-compose") is not None:
        backend = "docker-compose"
    if backend is None:
        print(
            f"{prog}: no compose backend on PATH. `podman compose` needs one:\n"
            "  pipx install podman-compose",
            file=sys.stderr,
        )
        sys.exit(1)

    if with_systemd:
        # The system install path needs systemctl + root for the
        # Quadlet install + service start. `deploy` / `upgrade` call us
        # with with_systemd=True only when we're already running as
        # root, so the geteuid check is a safety net for direct callers
        # (init --systemd just writes files, doesn't enter this branch).
        if shutil.which("systemctl") is None:
            print(f"{prog}: the system install needs systemctl on PATH", file=sys.stderr)
            sys.exit(1)
        if os.geteuid() != 0:
            print(
                f"{prog}: the system install writes units under {QUADLET_SYSTEM_DIR} "
                "and runs systemctl, both of which require root.\n"
                f"  sudo {prog} ...",
                file=sys.stderr,
            )
            sys.exit(1)

    return backend


def _run(
    cmd: list[str],
    *,
    cwd: Path | None = None,
    env: dict[str, str] | None = None,
    check: bool = True,
) -> int:
    """Run ``cmd`` with stdout/stderr inherited so the operator sees
    progress. Factored so tests can patch this single point.

    With ``check`` (the default), exits 1 on non-zero status. With
    ``check=False`` it instead prints a warning and returns the exit
    code, letting the caller press on -- used by ``purge`` where a
    teardown step hitting an already-gone service / container is
    expected, not fatal."""
    proc = subprocess.run(cmd, cwd=cwd, env=env, check=False)
    if proc.returncode != 0:
        if check:
            print(
                f"\nbty-lab: `{' '.join(cmd)}` exited {proc.returncode}",
                file=sys.stderr,
            )
            sys.exit(1)
        print(
            f"  (ignored) `{' '.join(cmd)}` exited {proc.returncode}",
            file=sys.stderr,
        )
    return proc.returncode


def _compose(dest: Path, args: list[str], *, check: bool = True) -> None:
    """Invoke `podman compose` in ``dest`` with the deploy's envvars file
    already wired up via ``--env-file`` so the operator doesn't need
    ``COMPOSE_ENV_FILES`` exported."""
    _run(
        ["podman", "compose", "--env-file", "envvars", *args],
        cwd=dest,
        check=check,
    )


def _systemctl(args: list[str], *, check: bool = True) -> None:
    """Invoke systemctl with output inherited."""
    _run(["systemctl", *args], check=check)


def _chown_to_sudo_user(paths: list[Path]) -> tuple[str, int, int] | None:
    """When running under ``sudo`` (root + ``$SUDO_USER`` set), chown
    each path to the original operator so they can edit ``envvars``
    (and inspect the rest of the deploy dir) without needing ``sudo``
    afterwards. Returns ``(user, uid, gid)`` on success, or ``None``
    when the chown was skipped (not running under sudo, or
    ``$SUDO_USER`` is missing from ``/etc/passwd``).

    Does NOT recurse into ``data/`` -- those bind-mount dirs are
    populated by the containers and get the container-uid ownership
    podman wants; chowning them out from under podman would break
    rootful bind-mount semantics."""
    sudo_user = os.environ.get("SUDO_USER")
    if os.geteuid() != 0 or not sudo_user:
        return None
    try:
        import pwd

        pw = pwd.getpwnam(sudo_user)
    except KeyError:
        return None
    for p in paths:
        if p.exists():
            os.chown(p, pw.pw_uid, pw.pw_gid)
    return (sudo_user, pw.pw_uid, pw.pw_gid)


def _prepare_data_dirs(data_dir_abs: Path) -> list[Path]:
    """Pre-create the bind-mount targets that ``compose.yml`` mounts
    into ``withcache`` (`/data`) and ``bty-web`` (`/var/lib/bty`), and
    open them up so the containers can write regardless of what UID
    their image's ``USER`` directive resolves to.

    Why world-writable: withcache's image runs as ``app``, bty-web's
    as ``bty``. Those UIDs vary across image rebuilds and don't match
    the host operator's UID. ``chmod 0o777`` on these two appliance-
    local state dirs avoids a per-image UID lookup AND respects the
    image authors' choice to drop privileges inside the container.

    The bty-tftp service has no volume mount (its NBPs are baked into
    the image), so it's not part of this dance.

    Returns the list of created paths for the ``_step`` log line."""
    created: list[Path] = []
    for sub in ("withcache", "bty"):
        p = data_dir_abs / sub
        p.mkdir(parents=True, exist_ok=True)
        p.chmod(0o777)
        created.append(p)
    return created


def _install_quadlets(dest: Path, *, force: bool) -> list[Path]:
    """Copy ``dest/quadlet/*.container`` to ``QUADLET_SYSTEM_DIR``.
    Returns the list of installed paths. Refuses to overwrite existing
    units unless ``force``."""
    src_dir = dest / "quadlet"
    QUADLET_SYSTEM_DIR.mkdir(parents=True, exist_ok=True)
    installed: list[Path] = []
    for unit in sorted(src_dir.glob("*.container")):
        target = QUADLET_SYSTEM_DIR / unit.name
        if target.exists() and not force:
            raise FileExistsError(f"{target} already exists; pass --force to overwrite.")
        shutil.copy2(unit, target)
        installed.append(target)
    return installed


def _remove_quadlets() -> list[Path]:
    """Delete bty's Quadlet unit files from :data:`QUADLET_SYSTEM_DIR`.
    Inverse of :func:`_install_quadlets`. Returns the removed paths;
    units that aren't present are silently skipped (idempotent)."""
    removed: list[Path] = []
    for name in ("bty-web.container", "withcache.container", "bty-tftp.container"):
        target = QUADLET_SYSTEM_DIR / name
        if target.exists():
            target.unlink()
            removed.append(target)
    return removed


def _confirm(prompt: str, *, assume_yes: bool) -> bool:
    """y/N confirmation gate for destructive operations.

    Returns True to proceed. ``assume_yes`` skips the prompt (for
    scripted / unattended runs). On a non-interactive stdin (no TTY)
    without ``assume_yes`` it refuses rather than block or guess -- a
    purge shouldn't fire unattended just because it was piped."""
    if assume_yes:
        return True
    if not sys.stdin.isatty():
        print(
            "  refusing to proceed unattended: stdin is not a TTY. Re-run with --yes to confirm.",
            file=sys.stderr,
        )
        return False
    try:
        ans = input(f"{prompt} [y/N] ").strip().lower()
    except EOFError:
        return False
    return ans in ("y", "yes")


def init_main(argv: list[str] | None = None, *, prog: str = "bty-lab init") -> None:
    """The ``bty-lab init`` subcommand: emit the compose deploy.

    Invoked via :func:`main` (which strips the ``init`` keyword from
    argv before handing off here)."""
    parser = argparse.ArgumentParser(
        prog=prog,
        description=(
            "Generate a ready-to-run podman/docker compose deployment "
            "for bty-web + withcache (plus optional Quadlet units). "
            "The emitted compose.yml pins the bty-web / bty-tftp images "
            "to the same version as the bty CLI that generated it. "
            "Re-runnable: pass --force to refresh an existing deploy "
            "directory against a newer bty release."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "dest",
        nargs="?",
        type=Path,
        default=DEFAULT_DEST,
        help=f"Output directory. Default: {DEFAULT_DEST}",
    )
    parser.add_argument(
        "--print",
        dest="print_only",
        action="store_true",
        help="Print compose.yml to stdout instead of writing files. "
        "Useful for piping into `podman compose -f - up`.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files. Without this flag bty-lab "
        "refuses to clobber an existing compose.yml / envvars.example.",
    )
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=None,
        help="Where bty/withcache host state lives. Default: <DEST>/data. "
        "Pass an absolute path on a dedicated disk for larger fleets "
        "(the Quadlet units, if --systemd is also passed, bake this path "
        "in as an absolute reference).",
    )
    parser.add_argument(
        "--systemd",
        action="store_true",
        help="Also emit Podman Quadlet units under <DEST>/quadlet/ for "
        "systemd-managed auto-start on boot.",
    )
    args = parser.parse_args(argv)

    version = bty.__version__

    if args.print_only:
        sys.stdout.write(_compose_yaml(version))
        return

    dest: Path = args.dest
    data_dir: Path = args.data_dir if args.data_dir is not None else (dest / "data")
    # Absolutise for the Quadlet units (systemd does not run in the
    # operator's cwd) and for the envvars hint text. The compose file
    # itself uses the literal ``./data`` default + ${BTY_HOST_DATA_DIR}
    # override so relative paths still work when operators ``cd`` into
    # the deploy dir.
    data_dir_abs = data_dir.resolve()

    try:
        written = _emit_deploy_files(
            dest,
            data_dir_abs=data_dir_abs,
            version=version,
            with_systemd=args.systemd,
            force=args.force,
        )
    except FileExistsError as exc:
        print(f"{prog}: {exc}", file=sys.stderr)
        sys.exit(1)
    except PermissionError as exc:
        # The mkdir-parents inside _write fails this way when the operator
        # points init at a system path like /opt/bty without first making
        # it writable. Without this branch the failure is a bare Python
        # traceback the operator might miss inside a uvx wrapper.
        reason = exc.strerror or "Permission denied"
        print(f"{prog}: cannot write to {dest}: {reason}", file=sys.stderr)
        print(
            "hint: create the directory with the operator's ownership first:\n"
            f"  sudo mkdir -p {dest}\n"
            f'  sudo chown "$USER:$USER" {dest}\n'
            f"  {prog} {dest}",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"{prog}: wrote {len(written)} files to {dest}/", file=sys.stderr)
    for p in written:
        print(f"  {p.relative_to(dest.parent) if dest.parent != Path() else p}", file=sys.stderr)

    # Compose-backend probe. `podman compose` shells out to podman-compose
    # (or docker-compose). When neither is on PATH the operator hits a
    # cryptic "looking up compose provider failed" later -- surface it
    # here instead. Silent on success.
    if shutil.which("podman-compose") is None and shutil.which("docker-compose") is None:
        print(
            f"\n{prog}: heads-up -- no compose backend on PATH; "
            "`podman compose` will fail. Install one:\n"
            "  pipx install podman-compose",
            file=sys.stderr,
        )

    print(
        f"\nNext:\n"
        f"  cd {dest}\n"
        f'  cp envvars.example envvars && "${{EDITOR:-vi}}" envvars\n'
        f"  COMPOSE_ENV_FILES=envvars podman compose --profile tftp up -d",
        file=sys.stderr,
    )
    print(
        f"\nFor a one-shot stand-up (auto-fills envvars + brings up the\n"
        f"stack), use `{prog.replace(' init', '')} deploy` instead.",
        file=sys.stderr,
    )


def deploy_main(argv: list[str] | None = None, *, prog: str = "bty-lab deploy") -> None:
    """The ``bty-lab deploy`` subcommand: emit files, auto-fill envvars
    with detected ``HOST_ADDR`` + ``"bty"`` admin passwords, then bring
    the stack up via ``podman compose ... up -d``.

    Mode is auto-detected from the operator's euid:

    - **root** ("system install"): includes the TFTP sidecar
      (``--profile tftp``), installs Quadlet units under
      :data:`QUADLET_SYSTEM_DIR`, runs ``systemctl daemon-reload``,
      starts the services. Stack survives host reboots.
    - **non-root** ("user install"): compose-only. Skips the TFTP
      sidecar (binds privileged UDP/69), no Quadlet install, no
      systemctl. Operator must re-run ``podman compose up -d`` after
      host reboot. UEFI HTTP Boot works; legacy BIOS PXE clients
      need TFTP and so won't work in this mode.

    Side-effecting by design -- prefer :func:`init_main` when you want
    the files without the stand-up. ``--force`` overwrites existing
    files (compose.yml, envvars, Quadlet units); it never bypasses
    missing prereqs."""
    parser = argparse.ArgumentParser(
        prog=prog,
        description=(
            "Stand up the bty-web + withcache compose stack in one shot. "
            "Auto-detects install mode from your euid: as root, does the "
            "full install (TFTP sidecar + Podman Quadlet units installed "
            f"to {QUADLET_SYSTEM_DIR} + systemctl start, so the stack "
            "survives reboots); as a regular user, does the compose-only "
            "install (no TFTP, no autostart). The user-install path "
            "prints the limitations + re-run command at the end so it's "
            "easy to upgrade to a system install later."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "dest",
        nargs="?",
        type=Path,
        default=DEFAULT_DEST,
        help=f"Output directory. Default: {DEFAULT_DEST}",
    )
    parser.add_argument(
        "-f",
        "--force",
        action="store_true",
        help="Overwrite existing compose.yml / envvars / Quadlet units. "
        "Does NOT bypass missing prereqs (podman / podman-compose / systemctl).",
    )
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=None,
        help="Where bty/withcache host state lives. Default: <DEST>/data. "
        "Pass an absolute path on a dedicated disk for larger fleets.",
    )
    parser.add_argument(
        "--host-addr",
        type=str,
        default=None,
        help="Override auto-detected HOST_ADDR (the LAN IP booting clients "
        "fetch images + boot scripts from). When omitted, deploy probes the "
        "kernel's outbound-route IP and uses that.",
    )
    args = parser.parse_args(argv)

    version = bty.__version__
    dest: Path = args.dest
    data_dir: Path = args.data_dir if args.data_dir is not None else (dest / "data")
    data_dir_abs = data_dir.resolve()

    is_root = os.geteuid() == 0
    mode_label = "system install [root]" if is_root else "user install [non-root]"
    will_chown = is_root and bool(os.environ.get("SUDO_USER"))

    # Step total swings with mode + sudo presence. Counts: prereqs,
    # prereqs-OK, install-mode, emit-files, HOST_ADDR, passwords,
    # envvars, [chown?], prep-data, pull, start, [quadlets,
    # daemon-reload, start-svcs]*root, deploy-complete.
    total = 11 + (1 if will_chown else 0) + (3 if is_root else 0)
    _steps_begin(total)

    _step("checking prereqs")
    backend = _require_prereqs(with_systemd=is_root, prog=prog)
    _step("prereqs OK", detail=backend)
    _step("install mode", detail=mode_label)

    # Detect host_addr BEFORE emitting Quadlets so the bty-web unit can
    # bake the LAN IP into BTY_WITHCACHE_URL + BTY_TFTP_PROBE_HOST.
    # Quadlets don't expand env-file references the way Compose does, so
    # without this baked value the unit lands with a literal hostname
    # placeholder and bty-web's withcache + TFTP probe targets fail to
    # resolve at first start.
    host_addr = args.host_addr or _detect_host_addr()
    source = "auto-detected" if args.host_addr is None else "override"
    detail = f"{host_addr} [{source}]"
    if host_addr == "127.0.0.1":
        detail += "  WARNING: loopback fallback -- pass --host-addr"
    _step("HOST_ADDR set", detail=detail)

    _step(f"emitting compose files into {dest}")
    try:
        written = _emit_deploy_files(
            dest,
            data_dir_abs=data_dir_abs,
            version=version,
            with_systemd=is_root,
            force=args.force,
            host_addr=host_addr,
        )
    except FileExistsError as exc:
        print(f"\n{prog}: {exc}", file=sys.stderr)
        sys.exit(1)
    except PermissionError as exc:
        reason = exc.strerror or "Permission denied"
        print(f"\n{prog}: cannot write to {dest}: {reason}", file=sys.stderr)
        print(
            "hint: create the directory with the operator's ownership first:\n"
            f"  sudo mkdir -p {dest}\n"
            f'  sudo chown "$USER:$USER" {dest}\n'
            f"  {prog} {dest}",
            file=sys.stderr,
        )
        sys.exit(1)
    for p in written:
        print(f"  {p.relative_to(dest.parent) if dest.parent != Path() else p}", file=sys.stderr)

    # Admin passwords default to "bty" -- matches the historic PAM default
    # and keeps first-boot UX trivial (operator types "bty" once, no
    # scrollback hunting). Session secret stays random because it's
    # crypto material, not a typed password.
    withcache_pw = "bty"
    admin_pw = "bty"
    session_secret = _gen_secret(32)
    _step("set admin passwords", detail='"bty" (default -- change in envvars before exposing)')

    envvars_path = dest / "envvars"
    bty_toml_path = dest / "bty.toml"
    if envvars_path.exists() and not args.force:
        print(
            f"\n{prog}: {envvars_path} already exists; pass --force to overwrite "
            "(this would replace the operator's existing passwords).",
            file=sys.stderr,
        )
        sys.exit(1)
    envvars_path.write_text(
        _render_envvars_filled(
            host_addr=host_addr,
            withcache_pw=withcache_pw,
            admin_pw=admin_pw,
            session_secret=session_secret,
            data_dir_abs=str(data_dir_abs),
        ),
        encoding="utf-8",
    )
    _step("wrote envvars", detail=str(envvars_path))

    # v0.42+: bty.toml is the operator-facing config file. envvars
    # remains for compose substitution (HOST_ADDR / WITHCACHE_ADMIN_PASSWORD)
    # but every BTY_* knob now lives here. The compose / Quadlet
    # bind-mounts this into the container at /etc/bty/bty.toml.
    if bty_toml_path.exists() and not args.force:
        print(
            f"\n{prog}: {bty_toml_path} already exists; pass --force to overwrite "
            "(this would replace the operator's existing config + session secret).",
            file=sys.stderr,
        )
        sys.exit(1)
    bty_toml_path.write_text(
        _render_bty_toml(
            host_addr=host_addr,
            admin_pw=admin_pw,
            session_secret=session_secret,
        ),
        encoding="utf-8",
    )
    # Mode 0640: contains the admin password + session secret in
    # plaintext, so operator + group readable but not world-readable.
    bty_toml_path.chmod(0o640)
    _step("wrote bty.toml", detail=str(bty_toml_path))

    # Hand the deploy dir back to the original operator so they can
    # edit envvars / inspect compose.yml without sudo afterwards. Only
    # fires under `sudo bty-lab deploy ...` (root + SUDO_USER set);
    # silent no-op when deploy was invoked as the operator already.
    chown_info = _chown_to_sudo_user([dest, *written, envvars_path, bty_toml_path])
    if chown_info is not None:
        user, _uid, _gid = chown_info
        _step("handed deploy dir to operator", detail=user)

    # Pre-create + open up the volume-mount targets BEFORE compose up.
    # Without this, withcache (USER app) and bty-web (USER bty) can't
    # write under data/ on the rootful host bind-mount and crash on
    # first start. See _prepare_data_dirs for the full why.
    created = _prepare_data_dirs(data_dir_abs)
    _step("prepared data dirs", detail=" ".join(str(p) for p in created))

    # Root mode pulls images via compose (warm the registry cache), then
    # hands off lifecycle to Quadlet + systemd entirely. Critically: NO
    # ``compose up -d`` in root mode -- the Quadlet-managed services bind
    # the same ports (8080 / 3000 / TFTP 69), so running both at once
    # blocks systemctl start with "port already in use". Non-root mode
    # keeps compose as the lifecycle (no Quadlets to hand off to).
    compose_args = ["--profile", "tftp"] if is_root else []
    _step("pulling images")
    _compose(dest, [*compose_args, "pull"])

    if is_root:
        # Tear down any leftover compose-managed containers from a prior
        # ``bty-lab deploy`` (this is idempotent -- no-op on a fresh
        # host). Without this, an upgrade-in-place that re-ran deploy
        # would have compose containers binding the ports the Quadlet
        # services need, and systemctl start would fail.
        _step("clearing compose-managed containers")
        _compose(dest, [*compose_args, "down"])

        _step(f"installing Quadlet units to {QUADLET_SYSTEM_DIR}")
        try:
            installed = _install_quadlets(dest, force=args.force)
        except FileExistsError as exc:
            print(f"\n{prog}: {exc}", file=sys.stderr)
            sys.exit(1)
        for p in installed:
            print(f"  {p}", file=sys.stderr)

        _step("systemctl daemon-reload")
        _systemctl(["daemon-reload"])

        _step("starting systemd services")
        _systemctl(["start", *_SYSTEMD_SERVICES])
    else:
        _step("starting stack")
        _compose(dest, [*compose_args, "up", "-d"])

    print("", file=sys.stderr)
    _step("deploy complete", detail=mode_label)
    print(
        f"  bty-web UI:  http://{host_addr}:8080/ui   (login: {admin_pw} / {admin_pw})\n"
        f"  withcache:   http://{host_addr}:3000/     (login: {withcache_pw} / {withcache_pw})\n"
        f"\n"
        f"  Change the default passwords in {envvars_path} before exposing\n"
        f"  the host past a trusted LAN.",
        file=sys.stderr,
    )

    if not is_root:
        # Loud + specific user-mode limitations so the operator knows
        # what they didn't get and exactly how to upgrade to a system
        # install when they're ready.
        print(
            "\n"
            f"  Heads up: this was a user install (non-root). Active limitations:\n"
            "    - No autostart on host reboot. Restart manually after a reboot:\n"
            f"        cd {dest} && COMPOSE_ENV_FILES=envvars podman compose up -d\n"
            "    - No TFTP sidecar (binds privileged UDP/69 -- needs root).\n"
            "      UEFI HTTP Boot works; legacy BIOS PXE clients won't.\n"
            "\n"
            "  Upgrade to a system install (installs Quadlet units +\n"
            "  systemctl autostart + TFTP sidecar) by re-running as root:\n"
            f"    sudo {prog} {dest} --force",
            file=sys.stderr,
        )


def upgrade_main(argv: list[str] | None = None, *, prog: str = "bty-lab upgrade") -> None:
    """The ``bty-lab upgrade`` subcommand: re-emit compose + Quadlet
    units against the current CLI's bty version, preserve ``envvars`` +
    ``data/``, then ``podman compose pull`` + restart. Detects a
    Quadlet-managed stack from installed units under
    :data:`QUADLET_SYSTEM_DIR` and adds ``systemctl daemon-reload`` +
    service restart in that case."""
    parser = argparse.ArgumentParser(
        prog=prog,
        description=(
            "Upgrade an existing bty-lab deploy in place. Regenerates "
            "compose.yml (image tags pinned to this CLI's bty version) "
            "and Quadlet units, preserves envvars + data/, then pulls "
            "new images and restarts the stack. Auto-detects whether "
            "the stack is Quadlet-managed (units under "
            f"{QUADLET_SYSTEM_DIR}) and uses systemctl in that case."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "dest",
        nargs="?",
        type=Path,
        default=DEFAULT_DEST,
        help=f"Deploy directory. Default: {DEFAULT_DEST}",
    )
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=None,
        help="Override BTY_HOST_DATA_DIR if envvars sets it. Default: <DEST>/data.",
    )
    args = parser.parse_args(argv)

    version = bty.__version__
    dest: Path = args.dest
    data_dir: Path = args.data_dir if args.data_dir is not None else (dest / "data")
    data_dir_abs = data_dir.resolve()

    compose_path = dest / "compose.yml"
    envvars_path = dest / "envvars"
    if not compose_path.exists():
        print(
            f"{prog}: no compose.yml in {dest}; run `bty-lab deploy {dest}` first.",
            file=sys.stderr,
        )
        sys.exit(1)
    if not envvars_path.exists():
        print(
            f"{prog}: no envvars in {dest}; an upgrade preserves envvars but it "
            "must already exist. Did you mean `bty-lab deploy`?",
            file=sys.stderr,
        )
        sys.exit(1)

    # Detect Quadlet-managed stack by presence of any installed unit.
    quadlet_managed = any(
        (QUADLET_SYSTEM_DIR / u).exists()
        for u in ("bty-web.container", "withcache.container", "bty-tftp.container")
    )
    is_root = os.geteuid() == 0

    # Quadlet refresh + systemctl restart need root. If the stack is
    # Quadlet-managed and we're not root, refuse cleanly -- a compose
    # restart would race the running systemd-managed containers.
    if quadlet_managed and not is_root:
        print(
            f"{prog}: {dest} is Quadlet-managed (system install) but "
            "you're not root.\n"
            "  Quadlet unit refresh + systemctl restart need root. "
            f"Re-run as:\n"
            f"    sudo {prog} {dest}",
            file=sys.stderr,
        )
        sys.exit(1)

    mode_label = "system install [root]" if is_root else "user install [non-root]"

    # Step total for upgrade. Counts: prereqs, prereqs-OK, install-mode,
    # regen-files, envvars-preserved, bty.toml-migrated-or-preserved,
    # prep-data, pull, [quadlets, daemon-reload, restart-svcs]*quadlet
    # OR [restart-stack]*compose, upgrade-complete.
    total = 9 + (3 if quadlet_managed else 1)
    _steps_begin(total)

    _step("checking prereqs")
    backend = _require_prereqs(with_systemd=is_root, prog=prog)
    _step("prereqs OK", detail=backend)
    _step("install mode", detail=mode_label)

    _step(
        f"regenerating compose files [bty {version}]",
        detail="Quadlet-managed" if quadlet_managed else "compose-managed",
    )
    # Read HOST_ADDR back out of the preserved envvars so the regenerated
    # Quadlet keeps the operator's committed value (re-detecting would
    # flap if the host's interface order or LAN address changed since
    # the original deploy).
    host_addr = _read_envvars_host_addr(envvars_path)
    written = _emit_deploy_files(
        dest,
        data_dir_abs=data_dir_abs,
        version=version,
        with_systemd=is_root,
        force=True,
        host_addr=host_addr,
    )
    for p in written:
        print(f"  {p.relative_to(dest.parent) if dest.parent != Path() else p}", file=sys.stderr)
    _step("envvars preserved", detail=str(envvars_path))

    # v0.42 in-place upgrade path: v0.41 deploys don't have a
    # bty.toml on disk but the regenerated compose / Quadlet expect
    # one at <dest>/bty.toml (the container bind-mount target).
    # Migrate from the existing envvars so operator-tuned values
    # (admin password, session secret) carry over to the TOML; an
    # already-present bty.toml is preserved as-is (operator may have
    # edited it via the Settings page).
    bty_toml_path = dest / "bty.toml"
    if bty_toml_path.exists():
        _step("bty.toml preserved", detail=str(bty_toml_path))
    else:
        bty_toml_path.write_text(
            _envvars_to_bty_toml(envvars_path, host_addr=host_addr),
            encoding="utf-8",
        )
        bty_toml_path.chmod(0o640)
        _step("migrated bty.toml from envvars", detail=str(bty_toml_path))

    # Same data-dir prep as deploy_main -- idempotent, so re-running
    # upgrade on an already-running stack is a no-op.
    created = _prepare_data_dirs(data_dir_abs)
    _step("prepared data dirs", detail=" ".join(str(p) for p in created))

    # Match the deploy-time profile choice: root pulls + restarts with
    # the TFTP sidecar, non-root skips it (UEFI HTTP-Boot only).
    compose_args = ["--profile", "tftp"] if is_root else []
    _step("pulling images")
    _compose(dest, [*compose_args, "pull"])

    if quadlet_managed:
        _step(f"refreshing Quadlet units in {QUADLET_SYSTEM_DIR}")
        installed = _install_quadlets(dest, force=True)
        for p in installed:
            print(f"  {p}", file=sys.stderr)

        _step("systemctl daemon-reload")
        _systemctl(["daemon-reload"])

        _step("restarting systemd services")
        _systemctl(["restart", *_SYSTEMD_SERVICES])
    else:
        _step("restarting stack")
        _compose(dest, [*compose_args, "up", "-d"])

    print("", file=sys.stderr)
    _step(f"upgrade to bty {version} complete", detail=mode_label)

    if not is_root and not quadlet_managed:
        # Same warning as deploy: surface what a non-root upgrade
        # didn't get them, so they can promote to a system install if
        # they want autostart / TFTP.
        print(
            "\n"
            "  Heads up: this was a user install upgrade (non-root). The\n"
            "  stack still has no autostart on host reboot, and no TFTP\n"
            "  sidecar. Promote to a system install:\n"
            f"    sudo bty-lab deploy {dest} --force",
            file=sys.stderr,
        )


def purge_main(argv: list[str] | None = None, *, prog: str = "bty-lab purge") -> None:
    """The ``bty-lab purge`` subcommand: tear a deploy back down -- the
    inverse of ``deploy`` / ``upgrade``.

    Stops and removes the running stack (compose-managed or
    Quadlet/systemd-managed, auto-detected the same way ``upgrade``
    does), and optionally deletes the host state and the deploy
    directory. Teardown steps are tolerant -- a service or container
    that's already gone is logged and skipped, not fatal -- so a
    half-removed deploy still purges cleanly. The destructive parts
    (data, deploy dir) are gated behind explicit flags AND a y/N
    confirmation (skip with --yes)."""
    parser = argparse.ArgumentParser(
        prog=prog,
        description=(
            "Tear down a bty-lab deploy: stop + remove the stack "
            "(compose or Quadlet/systemd, auto-detected) and, with the "
            "destructive flags, delete host state and the deploy "
            "directory. The inverse of deploy/upgrade. Idempotent: "
            "re-running on an already-removed stack is a no-op."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "dest",
        nargs="?",
        type=Path,
        default=DEFAULT_DEST,
        help=f"Deploy directory. Default: {DEFAULT_DEST}",
    )
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=None,
        help="Where bty/withcache host state lives, if not <DEST>/data "
        "(must match the original deploy's --data-dir).",
    )
    parser.add_argument(
        "--data",
        action="store_true",
        help="Also delete host state: <data-dir>/bty (state.db, image "
        "cache, backups) and <data-dir>/withcache (cached blobs). "
        "DESTRUCTIVE and irreversible.",
    )
    parser.add_argument(
        "--images",
        action="store_true",
        help="Also remove the pulled container images "
        "(bty-web / withcache / bty-tftp) for this CLI's bty version.",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Also delete the deploy directory itself (compose.yml, "
        "envvars, bty.toml, quadlet/). Implies --data. DESTRUCTIVE.",
    )
    parser.add_argument(
        "-y",
        "--yes",
        action="store_true",
        help="Skip the confirmation prompt (for scripted / unattended runs).",
    )
    args = parser.parse_args(argv)

    dest: Path = args.dest
    data_dir: Path = args.data_dir if args.data_dir is not None else (dest / "data")
    data_dir_abs = data_dir.resolve()

    remove_data = bool(args.data or args.all)
    remove_dir = bool(args.all)

    compose_path = dest / "compose.yml"
    quadlet_managed = any(
        (QUADLET_SYSTEM_DIR / u).exists()
        for u in ("bty-web.container", "withcache.container", "bty-tftp.container")
    )

    # Nothing to do: no compose file here AND no Quadlet units installed.
    if not compose_path.exists() and not quadlet_managed:
        print(
            f"{prog}: nothing to purge -- no compose.yml in {dest} and no bty "
            f"Quadlet units in {QUADLET_SYSTEM_DIR}.",
            file=sys.stderr,
        )
        sys.exit(1)

    if shutil.which("podman") is None:
        print(f"{prog}: podman is not on PATH; cannot tear down the stack.", file=sys.stderr)
        sys.exit(1)

    is_root = os.geteuid() == 0
    # Quadlet teardown (systemctl + unit removal under /etc) needs root.
    if quadlet_managed and not is_root:
        print(
            f"{prog}: {dest} is Quadlet-managed (system install) but you're "
            "not root.\n"
            "  Stopping services + removing units under "
            f"{QUADLET_SYSTEM_DIR} needs root. Re-run as:\n"
            f"    sudo {prog} {' '.join(argv or sys.argv[1:])}",
            file=sys.stderr,
        )
        sys.exit(1)

    mode_label = "Quadlet/systemd" if quadlet_managed else "compose"

    # Spell out exactly what's about to be removed before the gate, so
    # the operator sees the destructive scope (data / dir) up front.
    print(f"About to purge the {mode_label}-managed bty deploy at {dest}:", file=sys.stderr)
    if quadlet_managed:
        print(
            f"  - stop {', '.join(_SYSTEMD_SERVICES)} + remove their Quadlet units",
            file=sys.stderr,
        )
    else:
        print("  - podman compose down (containers + network)", file=sys.stderr)
    if args.images:
        print("  - remove the bty-web / withcache / bty-tftp images", file=sys.stderr)
    if remove_data:
        print(
            f"  - DELETE host state: {data_dir_abs}/bty and {data_dir_abs}/withcache",
            file=sys.stderr,
        )
    if remove_dir:
        print(f"  - DELETE the deploy directory: {dest}", file=sys.stderr)
    if not remove_data and not remove_dir:
        print(
            "  (host state in data/ and the deploy directory are KEPT; "
            "pass --data / --all to remove them)",
            file=sys.stderr,
        )

    if not _confirm("Proceed?", assume_yes=args.yes):
        print(f"{prog}: aborted; nothing was changed.", file=sys.stderr)
        sys.exit(1)

    # Step count: teardown (1) [+ unit-removal + daemon-reload when
    # Quadlet] [+ images] [+ data] [+ dir] + done.
    total = (
        1
        + (2 if quadlet_managed else 0)
        + int(args.images)
        + int(remove_data)
        + int(remove_dir)
        + 1
    )
    _steps_begin(total)

    if quadlet_managed:
        _step("stopping systemd services")
        # Tolerant: an already-stopped / never-started unit is fine.
        _systemctl(["stop", *_SYSTEMD_SERVICES], check=False)

        _step(f"removing Quadlet units from {QUADLET_SYSTEM_DIR}")
        removed = _remove_quadlets()
        for p in removed:
            print(f"  {p}", file=sys.stderr)

        _step("systemctl daemon-reload")
        _systemctl(["daemon-reload"], check=False)
        # Clear any lingering failed state for the now-gone units.
        _systemctl(["reset-failed", *_SYSTEMD_SERVICES], check=False)
    else:
        _step("tearing down compose stack")
        # --profile tftp so the sidecar is included regardless of how it
        # was brought up; --volumes only when we're also dropping data
        # (the generated compose uses bind-mounts, but a named-volume
        # deploy needs it). Tolerant: a not-running stack is fine.
        down_args = ["--profile", "tftp", "down", "--remove-orphans"]
        if remove_data:
            down_args.append("--volumes")
        if compose_path.exists():
            _compose(dest, down_args, check=False)
        else:
            print("  (no compose.yml; skipping compose down)", file=sys.stderr)

    if args.images:
        _step("removing container images")
        version = bty.__version__
        images = [
            f"ghcr.io/safl/bty-web:{version}",
            "ghcr.io/safl/withcache:latest",
            f"ghcr.io/safl/bty-tftp:{version}",
        ]
        # Tolerant: an image still in use elsewhere, or a tag that was
        # never pulled, shouldn't abort the purge.
        _run(["podman", "rmi", *images], check=False)

    if remove_data:
        _step("deleting host state")
        for sub in ("bty", "withcache"):
            target = data_dir_abs / sub
            if target.exists():
                shutil.rmtree(target, ignore_errors=True)
                print(f"  removed {target}", file=sys.stderr)
            else:
                print(f"  (absent) {target}", file=sys.stderr)

    if remove_dir:
        _step("deleting deploy directory")
        if dest.exists():
            shutil.rmtree(dest, ignore_errors=True)
            print(f"  removed {dest}", file=sys.stderr)
        else:
            print(f"  (absent) {dest}", file=sys.stderr)

    print("", file=sys.stderr)
    _step("purge complete", detail=mode_label)


def show_config_main(argv: list[str] | None = None, *, prog: str = "bty-lab show-config") -> None:
    """The ``bty-lab show-config`` subcommand: dump the effective
    Config + per-key provenance to stdout.

    Same loader as ``bty-web`` consults at startup, so an operator
    SSH'd into a host can answer "where does this value come from?"
    (default / which TOML file / which env var) without booting the
    server. Useful for debugging surprise behaviour without going
    through the UI -- and works even when bty-web is offline.

    ``--config PATH`` -- same flag as ``bty-web``; overrides the
    default search list.
    """
    parser = argparse.ArgumentParser(
        prog=prog,
        description=(
            "Print the effective bty.toml-driven config + per-key provenance "
            "(default / toml(<path>) / env(<NAME>)). Same loader as "
            "``bty-web`` boots from."
        ),
    )
    parser.add_argument(
        "--config",
        action="append",
        default=None,
        metavar="PATH",
        help=(
            "TOML config file OR directory of drop-ins. Repeatable; each later "
            "one overrides earlier per-key. Overrides the default search list "
            "($BTY_CONFIG_FILE / $BTY_CONFIG_DIR / /etc/bty / <state_dir>/bty.toml)."
        ),
    )
    args = parser.parse_args(argv)

    # Import here so ``bty-lab`` cold-startup stays standalone --
    # ``bty.web._config`` is itself stdlib-only, but the import path
    # is unnecessary unless the operator actually wants to inspect.
    try:
        from bty.web import _config as cfg_mod
    except ImportError as exc:
        print(
            f"{prog}: cannot import bty.web._config ({exc}); reinstall with "
            '`pipx install "bty-lab[web]"` if it was uninstalled.',
            file=sys.stderr,
        )
        sys.exit(1)

    paths: list[Path] | None = [Path(p) for p in args.config] if args.config else None
    loaded = cfg_mod.load_config(paths)
    cfg = loaded.cfg

    # Surface where the loader looked + which files contributed +
    # which file the Settings page would write back to. Operators
    # tracing "why isn't my change taking effect?" usually want this
    # first.
    print("# bty config")
    print(f"#   loaded files:    {', '.join(str(p) for p in loaded.loaded_files) or '(none)'}")
    print(f"#   primary toml:    {loaded.primary_toml or '(no writable bty.toml found)'}")
    print()

    from dataclasses import fields
    from typing import get_type_hints

    section_types = get_type_hints(cfg_mod.Config)
    for section_name, section_cls in section_types.items():
        print(f"[{section_name}]")
        section_obj = getattr(cfg, section_name)
        for fld in fields(section_cls):
            value = getattr(section_obj, fld.name)
            dotted = f"{section_name}.{fld.name}"
            source = loaded.sources.get(dotted, "default")
            # Pretty-format the value for the TOML-ish display: quote
            # strings, leave ints bare. Mirrors how the operator would
            # write it in bty.toml.
            rendered = f'"{value}"' if isinstance(value, str) else str(value)
            print(f"  {fld.name} = {rendered}    # {source}")
        print()


def main(argv: list[str] | None = None, *, prog: str = "bty-lab") -> None:
    """Console-script entry point for ``bty-lab``.

    Top-level dispatcher: recognises ``init`` and hands the rest of the
    argv to :func:`init_main`. With no subcommand (or ``--help``), prints
    a usage that also points operators at ``bty`` for the flash wizard --
    important because someone running ``pipx run bty-lab`` blind might
    actually be looking for the wizard.

    ``bty-lab`` is intentionally standalone: this module imports nothing
    from the ``[web]`` / ``[tui]`` extras, so a bare ``uvx bty-lab``
    cold-starts in the time it takes to download the wheel."""
    if argv is None:
        argv = sys.argv[1:]

    # Subcommand sniff. Done before argparse so each subcommand's own
    # argparse owns its ``--help`` text.
    if argv and argv[0] == "init":
        init_main(argv[1:], prog=f"{prog} init")
        return
    if argv and argv[0] == "deploy":
        deploy_main(argv[1:], prog=f"{prog} deploy")
        return
    if argv and argv[0] == "upgrade":
        upgrade_main(argv[1:], prog=f"{prog} upgrade")
        return
    if argv and argv[0] == "show-config":
        show_config_main(argv[1:], prog=f"{prog} show-config")
        return
    if argv and argv[0] == "purge":
        purge_main(argv[1:], prog=f"{prog} purge")
        return

    parser = argparse.ArgumentParser(
        prog=prog,
        description=(
            f"{prog}: bootstrap and manage a bty-web + withcache container deploy.\n\n"
            "Subcommands:\n"
            f"  {prog} init [DEST]      Emit ready-to-run compose files (no side effects).\n"
            f"  {prog} deploy [DEST]    Emit files + auto-fill envvars + bring up the\n"
            "                          stack. Auto-detects install mode from euid:\n"
            "                          as root, full system install (TFTP sidecar +\n"
            f"                          Quadlet units in {QUADLET_SYSTEM_DIR}\n"
            "                          + systemctl autostart); as a regular user,\n"
            "                          compose-only (no TFTP, no autostart, with a\n"
            "                          warning listing exactly what was skipped).\n"
            f"  {prog} upgrade [DEST]   Re-emit compose against this CLI's bty version,\n"
            "                          pull new images, restart the stack (preserves\n"
            "                          envvars + data/). Same root vs user mode rules.\n"
            f"  {prog} show-config      Print the effective bty.toml-driven config +\n"
            "                          per-key provenance (default / TOML file /\n"
            "                          env var). Useful for debugging without\n"
            "                          booting bty-web.\n"
            f"  {prog} purge [DEST]     Tear the stack back down (inverse of deploy):\n"
            "                          stop + remove containers (compose or Quadlet).\n"
            "                          --data also deletes host state, --all also the\n"
            "                          deploy dir; both gated by a y/N confirm.\n\n"
            "Pass --help to any subcommand for its full flag set.\n\n"
            "Quick start (full system install, recommended):\n"
            '  sudo mkdir -p /opt/bty && sudo chown "$USER:$USER" /opt/bty\n'
            "  sudo uvx bty-lab deploy /opt/bty\n\n"
            "Other commands in this distribution:\n"
            "  bty      Interactive flash wizard (TUI). Requires the [tui] extra:\n"
            "             pipx install 'bty-lab[tui]'\n"
            "           bty is also the default entry on the bty USB live env\n"
            "           and the netboot live env, where it runs on tty1 with\n"
            "           no extra setup -- the workstation install is mostly\n"
            "           useful for demos / contributor work.\n"
            "  bty-web  HTTP server (browser UI + REST + PXE plans). Usually\n"
            "           run as the published container; for local dev\n"
            "           install the [web] extra and run `bty-web`."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"{prog} {bty.__version__}",
    )
    # No positional / unknown args reach this point. parse_args handles
    # ``--help`` (exits 0) and ``--version`` (exits 0). Anything else
    # falls through to the help-and-exit-2 path below.
    parser.parse_args(argv)
    parser.print_help(sys.stderr)
    sys.exit(2)
