"""``bty-lab init`` -- emit a ready-to-run podman/docker compose
deployment of bty-web + withcache (with an optional Quadlet variant for
systemd auto-start).

The intent is to turn the first-boot ergonomics of a bty + withcache
host from "clone the repo, find the right files" into:

    uvx bty-lab init ./bty-host
    cd bty-host
    cp envvars.example envvars && "${EDITOR:-vi}" envvars
    podman compose up -d

The emitted ``compose.yml`` pins ``bty-web`` and ``bty-tftp`` to the
*exact* version of the CLI that produced it -- re-running the command
later regenerates the file against a newer release. ``withcache`` is an
external project and stays at ``:latest`` (it does not share bty's
release cadence).

``bty-lab`` is a separate console script from ``bty`` on purpose: the
flash wizard wants to stay single-purpose, and matching the script name
to the PyPI distribution lets ``uvx bty-lab ...`` and
``pipx run bty-lab ...`` work without ``--from``.

This module imports nothing from the ``[web]`` / ``[tui]`` extras so a
bare ``uvx bty-lab`` suffices to run it.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import bty

DEFAULT_DEST = Path("./bty-host")


def _compose_yaml(version: str) -> str:
    """Render the compose.yml body for ``version``."""
    return f"""\
# Generated by `bty-lab init` (bty {version}).
# Re-run that command later (with --force) to refresh against a newer
# bty release; the bty-web / bty-tftp image tags below match the CLI
# version that emitted this file.
#
# Quickstart:
#   cp envvars.example envvars
#   "${{EDITOR:-vi}}" envvars                                  # set HOST_ADDR + passwords
#   export COMPOSE_ENV_FILES=envvars                           # once per shell, then:
#   podman compose up -d                                       # bty:       http://<host>:8080/ui
#                                                              # withcache: http://<host>:3000/
#
# (Without the export, pass --env-file envvars on every compose call.)
#
# BIOS PXE clients also need TFTP (UEFI HTTP-Boot does not):
#   podman compose --profile tftp up -d
#
# Upgrade:
#   uvx bty-lab init --force .                                 # regenerate against newer bty
#   podman compose pull && podman compose up -d
#
# Host state lives under ${{BTY_HOST_DATA_DIR:-./data}} -- bty under
# bty/, withcache under withcache/. Move/back-up those dirs to migrate
# to another host.

services:
  withcache:
    image: ghcr.io/safl/withcache:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      WITHCACHE_ADMIN_PASSWORD: ${{WITHCACHE_ADMIN_PASSWORD:?set in envvars}}
    volumes:
      - ${{BTY_HOST_DATA_DIR:-./data}}/withcache:/data

  bty-web:
    image: ghcr.io/safl/bty-web:v{version}
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # bty-web auto-discovers withcache from this env var at boot --
      # no UI step needed. Set HOST_ADDR in envvars to this host's LAN
      # address (clients fetch images from it, so it must be reachable
      # from the booting machines -- not 127.0.0.1, not a container
      # name).
      BTY_WITHCACHE_URL: http://${{HOST_ADDR:?set HOST_ADDR to this host's LAN address}}:3000
      # Every other knob below is optional: empty string == unset (bty-web
      # treats them identically). Uncomment the matching line in envvars to
      # override; the compose layer plumbs each one straight through.
      BTY_ADMIN_PASSWORD: ${{BTY_ADMIN_PASSWORD:-}}
      BTY_BOOT_RELEASE_REPO: ${{BTY_BOOT_RELEASE_REPO:-}}
      BTY_TRUSTED_PROXY: ${{BTY_TRUSTED_PROXY:-}}
      BTY_SESSION_SECRET: ${{BTY_SESSION_SECRET:-}}
      BTY_MAX_UPLOAD_BYTES: ${{BTY_MAX_UPLOAD_BYTES:-}}
      BTY_CATALOG_MAX_PARALLEL: ${{BTY_CATALOG_MAX_PARALLEL:-}}
      BTY_HASH_MAX_PARALLEL: ${{BTY_HASH_MAX_PARALLEL:-}}
      BTY_BACKUP_MAX_PARALLEL: ${{BTY_BACKUP_MAX_PARALLEL:-}}
    volumes:
      - ${{BTY_HOST_DATA_DIR:-./data}}/bty:/var/lib/bty
    depends_on:
      - withcache

  tftp:
    image: ghcr.io/safl/bty-tftp:v{version}
    profiles: ["tftp"]
    restart: unless-stopped
    # TFTP's data transfer hops to an ephemeral UDP port, so the sidecar
    # uses host networking. The NBPs (incl. bty's embedded-chain
    # ipxe.efi) are baked into the image -- no volume, no shared data.
    network_mode: host
"""


def _env_example(default_data_dir: str) -> str:
    """Render the envvars.example body."""
    return f"""\
# Copy to envvars and edit. The compose file refuses to start unless
# HOST_ADDR and WITHCACHE_ADMIN_PASSWORD are set; everything below
# the REQUIRED block has a sane default and stays empty/unset unless
# you uncomment.

# ==== REQUIRED ====

# This host's LAN address. Booting clients fetch images + boot scripts
# from here, so it MUST be reachable from those machines -- NOT
# 127.0.0.1, NOT a container name.
HOST_ADDR=10.0.0.5

# Operator login for the withcache UI at http://<host>:3000/.
WITHCACHE_ADMIN_PASSWORD=change-me

# ==== STRONGLY RECOMMENDED ====

# Gates the bty-web operator UI at http://<host>:8080/ui (constant-
# time password compare). UNSET = UI open (bty-web logs a startup
# warning on first boot). Set this before exposing past a trusted
# LAN.
# BTY_ADMIN_PASSWORD=change-me

# ==== COMMON CUSTOMISATIONS ====

# Where state lives on the host. Default: ./data (relative to this
# directory). Point at a bigger disk for larger fleets:
# BTY_HOST_DATA_DIR={default_data_dir}

# ==== ADVANCED ====

# Override which GitHub repo bty fetches netboot artifacts (live env
# kernel/initrd/squashfs) from. Default: safl/bty. Useful when running
# off a fork or a private mirror.
# BTY_BOOT_RELEASE_REPO=your-fork/bty

# Trust the X-Forwarded-* headers from this CIDR or single address
# (set when bty-web sits behind nginx / traefik / Caddy so it can
# recover the original client's address + scheme for audit logs and
# absolute-URL generation). Default: unset (no header trust).
# BTY_TRUSTED_PROXY=10.0.0.0/8

# Pin a stable bty-web session-cookie secret. Default: a fresh random
# secret generated and persisted in state.db on first start (re-used
# across container restarts). Override only if you need the secret to
# be reproducible (multi-instance, blue/green) or rotated on a
# schedule.
# BTY_SESSION_SECRET=<32-byte hex>

# Per-request upload cap for the operator UI's image-upload form.
# Default: 200 GiB. Bump for very large images, drop for small
# fleets or untrusted networks.
# BTY_MAX_UPLOAD_BYTES=214748364800

# Concurrent-worker caps. Defaults are sane for most fleets; raise
# carefully if the host has the CPU + disk bandwidth, drop on small
# boxes (Raspberry Pi, low-spec mini-PCs).
# BTY_CATALOG_MAX_PARALLEL=2
# BTY_HASH_MAX_PARALLEL=1
# BTY_BACKUP_MAX_PARALLEL=1
"""


def _readme(version: str, *, with_systemd: bool) -> str:
    """Render the in-tree README the deploy dir ships with."""
    systemd_section = ""
    if with_systemd:
        systemd_section = """\

## Auto-start on boot (systemd via Quadlet)

The `quadlet/` directory holds Podman Quadlet units that systemd
generates services from. Install:

```sh
sudo cp quadlet/*.container /etc/containers/systemd/
sudo systemctl daemon-reload
sudo systemctl start withcache.service bty-web.service
# Optional, for BIOS PXE clients:
sudo systemctl start bty-tftp.service
```

`AutoUpdate=registry` lets `podman auto-update` (enable the
`podman-auto-update.timer`) pull new images and restart the services.
The units reference absolute paths under the `data/` directory next to
this README -- the path was baked in at `bty-lab` time. Move the
directory only by regenerating with `--data-dir <new-path>`.
"""

    return f"""\
# bty deploy

Generated by `bty-lab init` (bty {version}).

## Prerequisites

- `podman` (or `docker`).
- A compose backend. `podman compose` is a thin wrapper that
  auto-discovers one of `docker-compose`, `podman-compose`, or the
  docker compose plugin from PATH. If none is installed,
  `podman compose up -d` errors with "looking up compose provider
  failed". Fix: `pipx install podman-compose` (the lightest option).

## Quickstart

```sh
cp envvars.example envvars
"${{EDITOR:-vi}}" envvars                       # set HOST_ADDR + passwords

# Tell compose which env-file to load (once per shell):
export COMPOSE_ENV_FILES=envvars

podman compose up -d                            # bty:       http://<host>:8080/ui
                                                # withcache: http://<host>:3000/
```

If you'd rather not set the env var, pass ``--env-file envvars`` on
every compose call: ``podman compose --env-file envvars up -d``.

For BIOS PXE clients that bootstrap over TFTP (UEFI HTTP-Boot does
not):

```sh
podman compose up -d --profile tftp
```

bty-web auto-discovers withcache from the `BTY_WITHCACHE_URL` env var
that the compose file sets, so first-boot needs no UI configuration --
just `HOST_ADDR` + a password in `envvars`.

## Where the state lives

- `data/bty/`       -- bty-web's `/var/lib/bty` (state.db, image cache,
  backups). Bind-mounted into the container.
- `data/withcache/` -- withcache's `/data` (cached image blobs).

Override the parent path with `BTY_HOST_DATA_DIR=<absolute-path>` in
`envvars` to put state on a different disk.

## Upgrade

```sh
uvx bty-lab init --force .           # regenerate compose for newer bty
podman compose pull && podman compose up -d
```

The compose file pins bty-web / bty-tftp to the bty version that
generated this directory; re-running `bty-lab` with a newer bty CLI
bumps those pins. State in `data/` survives the restart.
{systemd_section}"""


def _quadlet_bty_web(version: str, data_dir_abs: Path) -> str:
    return f"""\
# Generated by `bty-lab init --systemd` (bty {version}).
# Install: sudo cp this file into /etc/containers/systemd/ then run
#   sudo systemctl daemon-reload && sudo systemctl start bty-web.service
#
# Edit Environment=BTY_WITHCACHE_URL: replace HOST_ADDR_HERE with this
# host's LAN address before installing.

[Unit]
Description=bty-web
After=network-online.target withcache.service
Wants=network-online.target

[Container]
Image=ghcr.io/safl/bty-web:v{version}
AutoUpdate=registry
PublishPort=8080:8080
Volume={data_dir_abs}/bty:/var/lib/bty:Z
Environment=BTY_WITHCACHE_URL=http://HOST_ADDR_HERE:3000

[Service]
Restart=always

[Install]
WantedBy=multi-user.target default.target
"""


def _quadlet_withcache(version: str, data_dir_abs: Path) -> str:
    return f"""\
# Generated by `bty-lab init --systemd` (bty {version}).
# Install: sudo cp this file into /etc/containers/systemd/ then run
#   sudo systemctl daemon-reload && sudo systemctl start withcache.service
#
# Edit Environment=WITHCACHE_ADMIN_PASSWORD before installing.

[Unit]
Description=withcache cache-host
After=network-online.target
Wants=network-online.target

[Container]
Image=ghcr.io/safl/withcache:latest
AutoUpdate=registry
PublishPort=3000:3000
Volume={data_dir_abs}/withcache:/data:Z
Environment=WITHCACHE_ADMIN_PASSWORD=change-me

[Service]
Restart=always

[Install]
WantedBy=multi-user.target default.target
"""


def _quadlet_bty_tftp(version: str) -> str:
    return f"""\
# Generated by `bty-lab init --systemd` (bty {version}).
# Optional: install only if BIOS clients PXE-boot via TFTP. UEFI
# HTTP-Boot does not need this sidecar.

[Unit]
Description=bty TFTP sidecar (BIOS PXE bootstrap)
After=network-online.target
Wants=network-online.target

[Container]
Image=ghcr.io/safl/bty-tftp:v{version}
AutoUpdate=registry
# TFTP data transfer uses an ephemeral UDP port; host networking is the
# simplest way to make that work. The NBPs are baked into the image.
Network=host

[Service]
Restart=always

[Install]
WantedBy=multi-user.target default.target
"""


def _write(path: Path, body: str, *, force: bool) -> None:
    """Write ``body`` to ``path``, creating parents. Refuse to overwrite
    unless ``force`` is True."""
    if path.exists() and not force:
        raise FileExistsError(
            f"{path} already exists; pass --force to overwrite "
            f"(re-runs of bty-lab re-render every file)."
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def init_main(argv: list[str] | None = None, *, prog: str = "bty-lab init") -> None:
    """The ``bty-lab init`` subcommand: emit the compose deploy.

    Invoked via :func:`main` (which strips the ``init`` keyword from
    argv before handing off here)."""
    parser = argparse.ArgumentParser(
        prog=prog,
        description=(
            "Generate a ready-to-run podman/docker compose deployment "
            "for bty-web + withcache (plus optional Quadlet units). "
            "The emitted compose.yml pins the bty-web / bty-tftp images "
            "to the same version as the bty CLI that generated it. "
            "Re-runnable: pass --force to refresh an existing deploy "
            "directory against a newer bty release."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "dest",
        nargs="?",
        type=Path,
        default=DEFAULT_DEST,
        help=f"Output directory. Default: {DEFAULT_DEST}",
    )
    parser.add_argument(
        "--print",
        dest="print_only",
        action="store_true",
        help="Print compose.yml to stdout instead of writing files. "
        "Useful for piping into `podman compose -f - up`.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files. Without this flag bty-lab "
        "refuses to clobber an existing compose.yml / envvars.example.",
    )
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=None,
        help="Where bty/withcache host state lives. Default: <DEST>/data. "
        "Pass an absolute path on a dedicated disk for larger fleets "
        "(the Quadlet units, if --systemd is also passed, bake this path "
        "in as an absolute reference).",
    )
    parser.add_argument(
        "--systemd",
        action="store_true",
        help="Also emit Podman Quadlet units under <DEST>/quadlet/ for "
        "systemd-managed auto-start on boot.",
    )
    args = parser.parse_args(argv)

    version = bty.__version__

    if args.print_only:
        sys.stdout.write(_compose_yaml(version))
        return

    dest: Path = args.dest
    data_dir: Path = args.data_dir if args.data_dir is not None else (dest / "data")
    # Absolutise for the Quadlet units (systemd does not run in the
    # operator's cwd) and for the envvars hint text. The compose file
    # itself uses the literal ``./data`` default + ${BTY_HOST_DATA_DIR}
    # override so relative paths still work when operators ``cd`` into
    # the deploy dir.
    data_dir_abs = data_dir.resolve()

    written: list[Path] = []

    try:
        compose_path = dest / "compose.yml"
        _write(compose_path, _compose_yaml(version), force=args.force)
        written.append(compose_path)

        env_path = dest / "envvars.example"
        _write(env_path, _env_example(str(data_dir_abs)), force=args.force)
        written.append(env_path)

        readme_path = dest / "README.md"
        _write(readme_path, _readme(version, with_systemd=args.systemd), force=args.force)
        written.append(readme_path)

        if args.systemd:
            quadlet_dir = dest / "quadlet"
            for fname, body in (
                ("bty-web.container", _quadlet_bty_web(version, data_dir_abs)),
                ("withcache.container", _quadlet_withcache(version, data_dir_abs)),
                ("bty-tftp.container", _quadlet_bty_tftp(version)),
            ):
                p = quadlet_dir / fname
                _write(p, body, force=args.force)
                written.append(p)
    except FileExistsError as exc:
        print(f"{prog}: {exc}", file=sys.stderr)
        sys.exit(1)

    # Pre-create the bind-mount roots so podman doesn't create them as
    # root-owned (when run as root) and so the operator can see where
    # state will land without starting the stack first.
    (data_dir / "bty").mkdir(parents=True, exist_ok=True)
    (data_dir / "withcache").mkdir(parents=True, exist_ok=True)

    print(f"{prog}: wrote {len(written)} files to {dest}/", file=sys.stderr)
    for p in written:
        print(f"  {p.relative_to(dest.parent) if dest.parent != Path() else p}", file=sys.stderr)
    print(f"\nNext: cd {dest}", file=sys.stderr)
    print('      cp envvars.example envvars && "${EDITOR:-vi}" envvars', file=sys.stderr)
    print(
        "      export COMPOSE_ENV_FILES=envvars && podman compose up -d",
        file=sys.stderr,
    )
    print(
        "      (BIOS PXE clients also need --profile tftp; UEFI HTTP-Boot does not.)",
        file=sys.stderr,
    )
    print(
        "      Prereq: podman compose needs a compose backend "
        "(`pipx install podman-compose` if missing).",
        file=sys.stderr,
    )


def main(argv: list[str] | None = None, *, prog: str = "bty-lab") -> None:
    """Console-script entry point for ``bty-lab``.

    Top-level dispatcher: recognises ``init`` and hands the rest of the
    argv to :func:`init_main`. With no subcommand (or ``--help``), prints
    a usage that also points operators at ``bty`` for the flash wizard --
    important because someone running ``pipx run bty-lab`` blind might
    actually be looking for the wizard.

    ``bty-lab`` is intentionally standalone: this module imports nothing
    from the ``[web]`` / ``[tui]`` extras, so a bare ``uvx bty-lab``
    cold-starts in the time it takes to download the wheel."""
    if argv is None:
        argv = sys.argv[1:]

    # Subcommand sniff. Done before argparse so the subcommand's own
    # argparse owns its ``--help`` text.
    if argv and argv[0] == "init":
        init_main(argv[1:], prog=f"{prog} init")
        return

    parser = argparse.ArgumentParser(
        prog=prog,
        description=(
            f"{prog}: bootstrap a bty-web + withcache container deploy.\n\n"
            f"Subcommands:\n"
            f"  {prog} init [DEST]   Emit a ready-to-run podman/docker compose\n"
            f"                       deploy for bty-web + withcache (+ optional\n"
            f"                       Quadlet units). Try:\n"
            f"                         uvx bty-lab init ./bty-host\n"
            f"                       Pass --help to the subcommand for its\n"
            f"                       full flag set.\n\n"
            "Other commands in this distribution:\n"
            "  bty      Interactive flash wizard (TUI). Requires the [tui] extra:\n"
            "             pipx install 'bty-lab[tui]'\n"
            "           bty is also the default entry on the bty USB live env\n"
            "           and the netboot live env, where it runs on tty1 with\n"
            "           no extra setup -- the workstation install is mostly\n"
            "           useful for demos / contributor work.\n"
            "  bty-web  HTTP server (browser UI + REST + PXE plans). Usually\n"
            "           run as the published container; for local dev\n"
            "           install the [web] extra and run `bty-web`."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"{prog} {bty.__version__}",
    )
    # No positional / unknown args reach this point. parse_args handles
    # ``--help`` (exits 0) and ``--version`` (exits 0). Anything else
    # falls through to the help-and-exit-2 path below.
    parser.parse_args(argv)
    parser.print_help(sys.stderr)
    sys.exit(2)
