#!/usr/bin/env python3
"""Package a live-build chroot's kernel + initrd + squashfs into a Pi-bootable raw disk image.

The Raspberry Pi boot ROM reads ``bootcode.bin`` / ``start*.elf`` /
``kernel*.img`` directly from FAT32 partition 1, not via MBR /
syslinux / grub. live-build has no native Pi image mode, so we run
``lb build --binary-images tar --architectures arm64`` to get a
``vmlinuz`` + ``initrd.img`` + ``filesystem.squashfs`` trio under
``binary/live/`` (the produced tarball is unused; ``tar`` mode is
chosen only because lb's netboot stage expects a ``tftpboot/``
directory the x86-only syslinux pipeline creates), then assemble a
3-partition raw image around them:

* **p1 FAT32, label ``RPIBOOT``, ~256 MiB, bootable**: the Pi
  firmware files from ``raspi-firmware`` (``bootcode.bin``, all
  ``start*.elf``, ``fixup*.dat``, every ``bcm*.dtb``), the
  ``vmlinuz`` and ``initrd.img`` lb produced, plus ``config.txt``
  and ``cmdline.txt`` we author. ``arm_64bit=1`` puts the firmware
  into 64-bit mode; ``dtparam=pciex1`` enables the Pi5/CM5 PCIe
  lane so a NVMe HAT enumerates.

* **p2 ext4, label ``BTY_LIVE``**: holds the squashfs as a single
  file ``/live/filesystem.squashfs``. live-boot's stock kernel
  cmdline ``boot=live components root=LABEL=BTY_LIVE rootwait``
  finds it by partition label and then by filename.

* **p3 exFAT, label ``BTY_IMAGES``, 32 MiB at bake**: the
  operator's flash-image scratch area. Auto-grows on first boot
  via the existing ``bty-usb-grow.service``.

The final ``.img.gz`` is what operators ``dd`` to a USB stick.
Designed to be invoked from ``cijoe/scripts/usb_rpi_build.py``;
runnable standalone for hand-testing too:

    sudo python3 bty-media/scripts/pack_rpi_img.py \\
        --build-dir cijoe/_build/usb-rpi \\
        --output _build/bty-usb-rpi-arm64-v0.47.0.img.gz \\
        --bty-version 0.47.0

Requires root (loop devices, mount, mkfs on a sparse file). On
``ubuntu-24.04-arm`` runners root is via ``sudo``.
"""

from __future__ import annotations

import argparse
import hashlib
import logging as log
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# Partition sizes in MiB. Chosen to fit the typical lb arm64 output
# (kernel ~60 MiB, initrd ~30 MiB, raspi-firmware ~30 MiB,
# squashfs 250-400 MiB) with slack.
FAT_SIZE_MIB = 256
EXFAT_SIZE_MIB = 32
EXT4_SLACK_MIB = 64  # added on top of the squashfs's actual size

# config.txt baked into p1. ``arm_64bit=1`` puts the Pi firmware
# into 64-bit mode for Pi4 / Pi5 / CM5 (default on Pi5 / CM5 but
# explicit so the same image works on Pi4). ``enable_uart=1``
# routes serial onto GPIO14/15 so a USB-TTL adapter sees the boot
# console. ``dtparam=pciex1`` enables the Pi5 / CM5 PCIe lane so a
# NVMe HAT enumerates as ``/dev/nvme0n1``; harmless on Pi4 (no
# PCIe lane to enable).
_CONFIG_TXT = """\
# bty USB-Pi flasher. Generated by bty-media/scripts/pack_rpi_img.py.
arm_64bit=1
enable_uart=1
dtparam=pciex1
kernel=vmlinuz
initramfs initrd.img followkernel
"""

# Single-line cmdline.txt. live-boot picks up the squashfs by
# rootfs label + file path. ``console=tty1`` for the HDMI console
# (operator-visible TUI); ``console=serial0,115200`` for the
# Pi firmware-overlaid debug UART (the right ``ttyAMAx`` per
# board revision is wired in by the raspi-firmware overlays).
# The last ``console=`` is systemd's default-stdout sink, so we
# put serial last to capture the early-boot stream when serial
# is the only diagnostic path.
_CMDLINE_TXT_FMT = (
    "boot=live components plymouth.enable=0 systemd.gpt_auto=0 "
    "console=tty1 console=serial0,115200 "
    "bty.version={version} "
    "root=LABEL=BTY_LIVE rootwait"
)


def main() -> int:
    log.basicConfig(level=log.INFO, format="%(message)s")
    args = _parse_args()

    build_dir = Path(args.build_dir).resolve()
    output = Path(args.output).resolve()
    version = args.bty_version

    binary_dir = build_dir / "binary"
    chroot_dir = build_dir / "chroot"
    firmware_dir = chroot_dir / "usr" / "lib" / "raspi-firmware"

    for required in (binary_dir, chroot_dir, firmware_dir):
        if not required.is_dir():
            log.error("required directory missing: %s", required)
            return 1

    vmlinuz_src, initrd_src, squashfs_src = _locate_lb_output(binary_dir)
    if vmlinuz_src is None or initrd_src is None or squashfs_src is None:
        log.error(
            "could not locate kernel + initrd + squashfs in %s: vmlinuz=%s initrd=%s squashfs=%s",
            binary_dir,
            vmlinuz_src,
            initrd_src,
            squashfs_src,
        )
        return 1
    log.info("found kernel:   %s (%d MiB)", vmlinuz_src, vmlinuz_src.stat().st_size >> 20)
    log.info("found initrd:   %s (%d MiB)", initrd_src, initrd_src.stat().st_size >> 20)
    log.info("found squashfs: %s (%d MiB)", squashfs_src, squashfs_src.stat().st_size >> 20)

    squashfs_size_mib = (squashfs_src.stat().st_size >> 20) + 1
    ext4_size_mib = squashfs_size_mib + EXT4_SLACK_MIB
    total_mib = 1 + FAT_SIZE_MIB + ext4_size_mib + EXFAT_SIZE_MIB
    log.info(
        "image layout: 1 MiB pad + FAT32 %d MiB + ext4 %d MiB + exFAT %d MiB = %d MiB total",
        FAT_SIZE_MIB,
        ext4_size_mib,
        EXFAT_SIZE_MIB,
        total_mib,
    )

    workdir = Path(tempfile.mkdtemp(prefix="pack-rpi-"))
    try:
        raw_img = workdir / "image.img"
        _run(["truncate", "-s", f"{total_mib}M", str(raw_img)])
        _write_partition_table(raw_img, FAT_SIZE_MIB, ext4_size_mib, EXFAT_SIZE_MIB)

        loop = _losetup(raw_img)
        try:
            _mkfs(loop)
            _populate_fat(
                loop,
                workdir,
                firmware_dir=firmware_dir,
                vmlinuz_src=vmlinuz_src,
                initrd_src=initrd_src,
                version=version,
            )
            _populate_ext4(loop, workdir, squashfs_src=squashfs_src)
            # p3 (exFAT BTY_IMAGES) is intentionally left empty; the
            # live env's bty-usb-grow.service auto-grows it on first
            # boot.
        finally:
            _run(["sudo", "losetup", "-d", loop], check=False)

        log.info("gzipping -> %s", output)
        output.parent.mkdir(parents=True, exist_ok=True)
        _gzip_to(raw_img, output)

        sha = _sha256(output)
        sha_path = output.with_suffix(output.suffix + ".sha256")
        sha_path.write_text(f"{sha}  {output.name}\n")
        log.info("sha256: %s", sha)
        log.info("wrote: %s", output)
        log.info("wrote: %s", sha_path)
    finally:
        shutil.rmtree(workdir, ignore_errors=True)

    return 0


# ---- step helpers ------------------------------------------------------------


def _locate_lb_output(binary_dir: Path) -> tuple[Path | None, Path | None, Path | None]:
    """Find the kernel + initrd + squashfs lb dropped under binary/.

    lb 20240208 emits ``binary/live/{vmlinuz, initrd.img,
    filesystem.squashfs}`` on the netboot path. The exact filenames
    are stable across architectures but the dir layout has drifted
    historically; scan defensively rather than hard-coding paths.
    """
    vmlinuz = initrd = squashfs = None
    for candidate in binary_dir.rglob("vmlinuz*"):
        if candidate.is_file():
            vmlinuz = candidate
            break
    for candidate in binary_dir.rglob("initrd*"):
        if candidate.is_file():
            initrd = candidate
            break
    for candidate in binary_dir.rglob("filesystem.squashfs"):
        if candidate.is_file():
            squashfs = candidate
            break
    return vmlinuz, initrd, squashfs


def _write_partition_table(img: Path, fat_mib: int, ext4_mib: int, exfat_mib: int) -> None:
    """Stamp a 3-entry MBR onto ``img``. sfdisk reads its layout from
    stdin; one line per partition (start + size + type + flags).
    ``size=`` in MiB-as-sectors lets us avoid arithmetic mistakes.
    """
    # 1 MiB front pad is the modern alignment convention (sfdisk
    # 2.36+ does it by default; explicit anyway for clarity).
    layout = (
        f"label: dos\n"
        f"start=1MiB, size={fat_mib}MiB, type=c, bootable\n"
        f"size={ext4_mib}MiB, type=83\n"
        f"size={exfat_mib}MiB, type=7\n"
    )
    log.info("sfdisk layout:\n%s", layout)
    proc = subprocess.run(
        ["sudo", "sfdisk", str(img)],
        input=layout.encode(),
        capture_output=True,
        check=False,
    )
    if proc.returncode != 0:
        log.error("sfdisk failed: %s", proc.stderr.decode(errors="replace"))
        raise SystemExit(proc.returncode)


def _losetup(img: Path) -> str:
    """Attach ``img`` to a free loop device with partition scanning
    enabled. Returns the loop device path (``/dev/loopN``)."""
    out = subprocess.check_output(["sudo", "losetup", "-fP", "--show", str(img)])
    loop = out.decode().strip()
    log.info("losetup: %s -> %s", img, loop)
    # Give udev a moment to materialise the partition device nodes.
    subprocess.run(["sudo", "udevadm", "settle", "--timeout=10"], check=False)
    return loop


def _mkfs(loop: str) -> None:
    """Format the three partitions on ``loop``."""
    _run(["sudo", "mkfs.vfat", "-F", "32", "-n", "RPIBOOT", f"{loop}p1"])
    _run(["sudo", "mkfs.ext4", "-q", "-L", "BTY_LIVE", f"{loop}p2"])
    _run(["sudo", "mkfs.exfat", "-L", "BTY_IMAGES", f"{loop}p3"])


def _populate_fat(
    loop: str,
    workdir: Path,
    *,
    firmware_dir: Path,
    vmlinuz_src: Path,
    initrd_src: Path,
    version: str,
) -> None:
    """Copy Pi firmware + kernel + initrd onto p1 and write the two
    text config files."""
    mnt = workdir / "p1"
    mnt.mkdir()
    _run(["sudo", "mount", f"{loop}p1", str(mnt)])
    try:
        # raspi-firmware contains bootcode.bin, start*.elf,
        # fixup*.dat, plus the DTBs in dtb/. Copy the lot.
        _run(f"sudo cp -r {firmware_dir}/. {mnt}/", shell=True)
        _run(["sudo", "cp", str(vmlinuz_src), f"{mnt}/vmlinuz"])
        _run(["sudo", "cp", str(initrd_src), f"{mnt}/initrd.img"])
        config_path = workdir / "config.txt"
        config_path.write_text(_CONFIG_TXT)
        _run(["sudo", "cp", str(config_path), f"{mnt}/config.txt"])
        cmdline_path = workdir / "cmdline.txt"
        cmdline_path.write_text(_CMDLINE_TXT_FMT.format(version=version) + "\n")
        _run(["sudo", "cp", str(cmdline_path), f"{mnt}/cmdline.txt"])
        log.info("populated p1 (RPIBOOT) with firmware + kernel + initrd + cfg")
    finally:
        _run(["sudo", "umount", str(mnt)], check=False)


def _populate_ext4(loop: str, workdir: Path, *, squashfs_src: Path) -> None:
    """Drop the squashfs into ``/live/filesystem.squashfs`` on p2."""
    mnt = workdir / "p2"
    mnt.mkdir()
    _run(["sudo", "mount", f"{loop}p2", str(mnt)])
    try:
        _run(["sudo", "mkdir", "-p", f"{mnt}/live"])
        _run(["sudo", "cp", str(squashfs_src), f"{mnt}/live/filesystem.squashfs"])
        log.info("populated p2 (BTY_LIVE) with /live/filesystem.squashfs")
    finally:
        _run(["sudo", "umount", str(mnt)], check=False)


def _gzip_to(raw: Path, output: Path) -> None:
    """``gzip -9 < raw > output`` via subprocess so we don't slurp
    the whole image into Python memory."""
    with output.open("wb") as out_fh:
        subprocess.run(
            ["gzip", "-9", "-c", str(raw)],
            stdout=out_fh,
            check=True,
        )


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _run(cmd, *, check: bool = True, shell: bool = False) -> None:
    log.info("$ %s", cmd if isinstance(cmd, str) else " ".join(cmd))
    proc = subprocess.run(cmd, check=False, shell=shell)
    if check and proc.returncode != 0:
        raise SystemExit(proc.returncode)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(__doc__ or "Pack a live-build trio into a Pi-bootable image").splitlines()[0]
    )
    parser.add_argument(
        "--build-dir",
        required=True,
        help="The lb build directory (contains binary/ + chroot/).",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to write the .img.gz to.",
    )
    parser.add_argument(
        "--bty-version",
        required=True,
        help="bty release version (lands on the kernel cmdline as bty.version=).",
    )
    return parser.parse_args()


if __name__ == "__main__":
    if os.geteuid() != 0 and shutil.which("sudo") is None:
        log.error("pack_rpi_img.py needs root (loop devices, mount, mkfs)")
        sys.exit(2)
    sys.exit(main())
